In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully.")

Libraries imported successfully.

In [3]:
from google.colab import files

uploaded = files.upload()

print("Uploaded files:")
for filename in uploaded.keys():
    print(filename)

Saving diabetic_data.csv to diabetic_data.csv
Uploaded files:
diabetic_data.csv

In [4]:
df = pd.read_csv("diabetic_data.csv", na_values=["?"])

print("Dataset loaded successfully.")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully.
Rows: 101766
Columns: 50

/tmp/ipykernel_2140/4082227467.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("diabetic_data.csv", na_values=["?"])

In [5]:
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),NaN,6,25,1,1,NaN,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,NaN,NaN,1,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),NaN,1,1,7,3,NaN,NaN,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),NaN,1,1,7,2,NaN,NaN,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),NaN,1,1,7,2,NaN,NaN,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),NaN,1,1,7,1,NaN,NaN,51,0,8,0,0,0,197,157,250,5,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [6]:
# Display all 50 column names with their index numbers
for i, column in enumerate(df.columns, start=1):
    print(f"{i:2}. {column}")

 1. encounter_id
 2. patient_nbr
 3. race
 4. gender
 5. age
 6. weight
 7. admission_type_id
 8. discharge_disposition_id
 9. admission_source_id
10. time_in_hospital
11. payer_code
12. medical_specialty
13. num_lab_procedures
14. num_procedures
15. num_medications
16. number_outpatient
17. number_emergency
18. number_inpatient
19. diag_1
20. diag_2
21. diag_3
22. number_diagnoses
23. max_glu_serum
24. A1Cresult
25. metformin
26. repaglinide
27. nateglinide
28. chlorpropamide
29. glimepiride
30. acetohexamide
31. glipizide
32. glyburide
33. tolbutamide
34. pioglitazone
35. rosiglitazone
36. acarbose
37. miglitol
38. troglitazone
39. tolazamide
40. examide
41. citoglipton
42. insulin
43. glyburide-metformin
44. glipizide-metformin
45. glimepiride-pioglitazone
46. metformin-rosiglitazone
47. metformin-pioglitazone
48. change
49. diabetesMed
50. readmitted

In [7]:
# Display the data type of every column
df.dtypes

encounter_id                 int64
patient_nbr                  int64
race                        object
gender                      object
age                         object
weight                      object
admission_type_id            int64
discharge_disposition_id     int64
admission_source_id          int64
time_in_hospital             int64
payer_code                  object
medical_specialty           object
num_lab_procedures           int64
num_procedures               int64
num_medications              int64
number_outpatient            int64
number_emergency             int64
number_inpatient             int64
diag_1                      object
diag_2                      object
diag_3                      object
number_diagnoses             int64
max_glu_serum               object
A1Cresult                   object
metformin                   object
repaglinide                 object
nateglinide                 object
chlorpropamide              object
glimepiride                 object
acetohexamide               object
glipizide                   object
glyburide                   object
tolbutamide                 object
pioglitazone                object
rosiglitazone               object
acarbose                    object
miglitol                    object
troglitazone                object
tolazamide                  object
examide                     object
citoglipton                 object
insulin                     object
glyburide-metformin         object
glipizide-metformin         object
glimepiride-pioglitazone    object
metformin-rosiglitazone     object
metformin-pioglitazone      object
change                      object
diabetesMed                 object
readmitted                  object
dtype: object

In [8]:
# Display every column with its data type without truncating the output
print(df.dtypes.to_string())

encounter_id                 int64
patient_nbr                  int64
race                        object
gender                      object
age                         object
weight                      object
admission_type_id            int64
discharge_disposition_id     int64
admission_source_id          int64
time_in_hospital             int64
payer_code                  object
medical_specialty           object
num_lab_procedures           int64
num_procedures               int64
num_medications              int64
number_outpatient            int64
number_emergency             int64
number_inpatient             int64
diag_1                      object
diag_2                      object
diag_3                      object
number_diagnoses             int64
max_glu_serum               object
A1Cresult                   object
metformin                   object
repaglinide                 object
nateglinide                 object
chlorpropamide              object
glimepiride                 object
acetohexamide               object
glipizide                   object
glyburide                   object
tolbutamide                 object
pioglitazone                object
rosiglitazone               object
acarbose                    object
miglitol                    object
troglitazone                object
tolazamide                  object
examide                     object
citoglipton                 object
insulin                     object
glyburide-metformin         object
glipizide-metformin         object
glimepiride-pioglitazone    object
metformin-rosiglitazone     object
metformin-pioglitazone      object
change                      object
diabetesMed                 object
readmitted                  object

In [9]:
# Count the missing values in every column and show them from highest to lowest
missing_values = df.isnull().sum().sort_values(ascending=False)

print(missing_values)

weight                      98569
max_glu_serum               96420
A1Cresult                   84748
medical_specialty           49949
payer_code                  40256
race                         2273
diag_3                       1423
diag_2                        358
diag_1                         21
patient_nbr                     0
time_in_hospital                0
admission_source_id             0
num_lab_procedures              0
encounter_id                    0
admission_type_id               0
discharge_disposition_id        0
gender                          0
age                             0
number_inpatient                0
number_emergency                0
number_outpatient               0
num_medications                 0
num_procedures                  0
number_diagnoses                0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [10]:
# Calculate the percentage of missing values in each column
missing_percentage = (
    df.isnull().mean() * 100
).sort_values(ascending=False)

print(missing_percentage)

weight                      96.858479
max_glu_serum               94.746772
A1Cresult                   83.277322
medical_specialty           49.082208
payer_code                  39.557416
race                         2.233555
diag_3                       1.398306
diag_2                       0.351787
diag_1                       0.020636
patient_nbr                  0.000000
time_in_hospital             0.000000
admission_source_id          0.000000
num_lab_procedures           0.000000
encounter_id                 0.000000
admission_type_id            0.000000
discharge_disposition_id     0.000000
gender                       0.000000
age                          0.000000
number_inpatient             0.000000
number_emergency             0.000000
number_outpatient            0.000000
num_medications              0.000000
num_procedures               0.000000
number_diagnoses             0.000000
metformin                    0.000000
repaglinide                  0.000000
nateglinide                  0.000000
chlorpropamide               0.000000
glimepiride                  0.000000
acetohexamide                0.000000
glipizide                    0.000000
glyburide                    0.000000
tolbutamide                  0.000000
pioglitazone                 0.000000
rosiglitazone                0.000000
acarbose                     0.000000
miglitol                     0.000000
troglitazone                 0.000000
tolazamide                   0.000000
examide                      0.000000
citoglipton                  0.000000
insulin                      0.000000
glyburide-metformin          0.000000
glipizide-metformin          0.000000
glimepiride-pioglitazone     0.000000
metformin-rosiglitazone      0.000000
metformin-pioglitazone       0.000000
change                       0.000000
diabetesMed                  0.000000
readmitted                   0.000000
dtype: float64

In [11]:
# Check the total number of completely duplicated rows in the dataset
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [12]:
# Count how many hospital encounters are recorded for each patient
patient_visit_counts = df["patient_nbr"].value_counts()

print("Total unique patients:", patient_visit_counts.nunique())
print("Unique patient IDs:", df["patient_nbr"].nunique())
print("Patients with multiple encounters:", (patient_visit_counts > 1).sum())
print("Maximum encounters for one patient:", patient_visit_counts.max())

Total unique patients: 25
Unique patient IDs: 71518
Patients with multiple encounters: 16773
Maximum encounters for one patient: 40

In [13]:
# Analyze how many hospital encounters each patient has in the dataset
print("Minimum encounters per patient:", patient_visit_counts.min())
print("Average encounters per patient:", round(patient_visit_counts.mean(), 2))
print("Maximum encounters per patient:", patient_visit_counts.max())

print("\nEncounter frequency:")
print(patient_visit_counts.value_counts().sort_index().head(15))

Minimum encounters per patient: 1
Average encounters per patient: 1.42
Maximum encounters per patient: 40

Encounter frequency:
count
1     54745
2     10434
3      3328
4      1421
5       717
6       346
7       207
8       111
9        70
10       42
11       20
12       19
13       14
14        5
15        9
Name: count, dtype: int64

In [14]:
# Check how many encounters belong to each readmission category
target_counts = df["readmitted"].value_counts()

print("Readmission category counts:")
print(target_counts)

print("\nReadmission category percentages:")
print((df["readmitted"].value_counts(normalize=True) * 100).round(2))

Readmission category counts:
readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

Readmission category percentages:
readmitted
NO     53.91
>30    34.93
<30    11.16
Name: proportion, dtype: float64

In [15]:
# Display the number of unique values and sample categories for each categorical column
categorical_columns = df.select_dtypes(include="object").columns

for column in categorical_columns:
    print(f"\n{'=' * 60}")
    print(f"Column: {column}")
    print(f"Unique values: {df[column].nunique(dropna=False)}")
    print(df[column].value_counts(dropna=False).head(10))

============================================================
Column: race
Unique values: 6
race
Caucasian          76099
AfricanAmerican    19210
NaN                 2273
Hispanic            2037
Other               1506
Asian                641
Name: count, dtype: int64

============================================================
Column: gender
Unique values: 3
gender
Female             54708
Male               47055
Unknown/Invalid        3
Name: count, dtype: int64

============================================================
Column: age
Unique values: 10
age
[70-80)     26068
[60-70)     22483
[50-60)     17256
[80-90)     17197
[40-50)      9685
[30-40)      3775
[90-100)     2793
[20-30)      1657
[10-20)       691
[0-10)        161
Name: count, dtype: int64

============================================================
Column: weight
Unique values: 10
weight
NaN          98569
[75-100)      1336
[50-75)        897
[100-125)      625
[125-150)      145
[25-50)         97
[0-25)          48
[150-175)       35
[175-200)       11
>200             3
Name: count, dtype: int64

============================================================
Column: payer_code
Unique values: 18
payer_code
NaN    40256
MC     32439
HM      6274
SP      5007
BC      4655
MD      3532
CP      2533
UN      2448
CM      1937
OG      1033
Name: count, dtype: int64

============================================================
Column: medical_specialty
Unique values: 73
medical_specialty
NaN                           49949
InternalMedicine              14635
Emergency/Trauma               7565
Family/GeneralPractice         7440
Cardiology                     5352
Surgery-General                3099
Nephrology                     1613
Orthopedics                    1400
Orthopedics-Reconstructive     1233
Radiologist                    1140
Name: count, dtype: int64

============================================================
Column: diag_1
Unique values: 717
diag_1
428    6862
414    6581
786    4016
410    3614
486    3508
427    2766
491    2275
715    2151
682    2042
434    2028
Name: count, dtype: int64

============================================================
Column: diag_2
Unique values: 749
diag_2
276    6752
428    6662
250    6071
427    5036
401    3736
496    3305
599    3288
403    2823
414    2650
411    2566
Name: count, dtype: int64

============================================================
Column: diag_3
Unique values: 790
diag_3
250    11555
401     8289
276     5175
428     4577
427     3955
414     3664
496     2605
403     2357
585     1992
272     1969
Name: count, dtype: int64

============================================================
Column: max_glu_serum
Unique values: 4
max_glu_serum
NaN     96420
Norm     2597
>200     1485
>300     1264
Name: count, dtype: int64

============================================================
Column: A1Cresult
Unique values: 4
A1Cresult
NaN     84748
>8       8216
Norm     4990
>7       3812
Name: count, dtype: int64

============================================================
Column: metformin
Unique values: 4
metformin
No        81778
Steady    18346
Up         1067
Down        575
Name: count, dtype: int64

============================================================
Column: repaglinide
Unique values: 4
repaglinide
No        100227
Steady      1384
Up           110
Down          45
Name: count, dtype: int64

============================================================
Column: nateglinide
Unique values: 4
nateglinide
No        101063
Steady       668
Up            24
Down          11
Name: count, dtype: int64

============================================================
Column: chlorpropamide
Unique values: 4
chlorpropamide
No        101680
Steady        79
Up             6
Down           1
Name: count, dtype: int64

============================================================
Column: glimepiride
Unique values: 4
glimepiride
No        96575
Steady     4670
Up          327
Down        194
Name: count, dtype: int64

============================================================
Column: acetohexamide
Unique values: 2
acetohexamide
No        101765
Steady         1
Name: count, dtype: int64

============================================================
Column: glipizide
Unique values: 4
glipizide
No        89080
Steady    11356
Up          770
Down        560
Name: count, dtype: int64

============================================================
Column: glyburide
Unique values: 4
glyburide
No        91116
Steady     9274
Up          812
Down        564
Name: count, dtype: int64

============================================================
Column: tolbutamide
Unique values: 2
tolbutamide
No        101743
Steady        23
Name: count, dtype: int64

============================================================
Column: pioglitazone
Unique values: 4
pioglitazone
No        94438
Steady     6976
Up          234
Down        118
Name: count, dtype: int64

============================================================
Column: rosiglitazone
Unique values: 4
rosiglitazone
No        95401
Steady     6100
Up          178
Down         87
Name: count, dtype: int64

============================================================
Column: acarbose
Unique values: 4
acarbose
No        101458
Steady       295
Up            10
Down           3
Name: count, dtype: int64

============================================================
Column: miglitol
Unique values: 4
miglitol
No        101728
Steady        31
Down           5
Up             2
Name: count, dtype: int64

============================================================
Column: troglitazone
Unique values: 2
troglitazone
No        101763
Steady         3
Name: count, dtype: int64

============================================================
Column: tolazamide
Unique values: 3
tolazamide
No        101727
Steady        38
Up             1
Name: count, dtype: int64

============================================================
Column: examide
Unique values: 1
examide
No    101766
Name: count, dtype: int64

============================================================
Column: citoglipton
Unique values: 1
citoglipton
No    101766
Name: count, dtype: int64

============================================================
Column: insulin
Unique values: 4
insulin
No        47383
Steady    30849
Down      12218
Up        11316
Name: count, dtype: int64

============================================================
Column: glyburide-metformin
Unique values: 4
glyburide-metformin
No        101060
Steady       692
Up             8
Down           6
Name: count, dtype: int64

============================================================
Column: glipizide-metformin
Unique values: 2
glipizide-metformin
No        101753
Steady        13
Name: count, dtype: int64

============================================================
Column: glimepiride-pioglitazone
Unique values: 2
glimepiride-pioglitazone
No        101765
Steady         1
Name: count, dtype: int64

============================================================
Column: metformin-rosiglitazone
Unique values: 2
metformin-rosiglitazone
No        101764
Steady         2
Name: count, dtype: int64

============================================================
Column: metformin-pioglitazone
Unique values: 2
metformin-pioglitazone
No        101765
Steady         1
Name: count, dtype: int64

============================================================
Column: change
Unique values: 2
change
No    54755
Ch    47011
Name: count, dtype: int64

============================================================
Column: diabetesMed
Unique values: 2
diabetesMed
Yes    78363
No     23403
Name: count, dtype: int64

============================================================
Column: readmitted
Unique values: 3
readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

In [16]:
# Separate the target variable from the input features
X = df.drop(columns=["readmitted"])
y = df["readmitted"]

print("Feature shape:", X.shape)
print("Target shape:", y.shape)
print("\nTarget values:")
print(y.value_counts())

Feature shape: (101766, 49)
Target shape: (101766,)

Target values:
readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

In [17]:
# Convert readmission status into a binary target: <30 days = 1, otherwise = 0
y_binary = y.map({
    "<30": 1,
    "NO": 0,
    ">30": 0
})

print("Binary target distribution:")
print(y_binary.value_counts())

print("\nBinary target percentages:")
print((y_binary.value_counts(normalize=True) * 100).round(2))

Binary target distribution:
readmitted
0    90409
1    11357
Name: count, dtype: int64

Binary target percentages:
readmitted
0    88.84
1    11.16
Name: proportion, dtype: float64

In [18]:
# Display summary statistics for all numerical features
numerical_columns = X.select_dtypes(include=["int64", "float64"]).columns

print("Numerical columns:")
print(list(numerical_columns))

print("\nSummary statistics:")
display(X[numerical_columns].describe().T)

Numerical columns:
['encounter_id', 'patient_nbr', 'admission_type_id', 'discharge_disposition_id', 'admission_source_id', 'time_in_hospital', 'num_lab_procedures', 'num_procedures', 'num_medications', 'number_outpatient', 'number_emergency', 'number_inpatient', 'number_diagnoses']

Summary statistics:

,count,mean,std,min,25%,50%,75%,max
encounter_id,101766.0,1.652016e+08,1.026403e+08,12522.0,84961194.0,152388987.0,2.302709e+08,443867222.0
patient_nbr,101766.0,5.433040e+07,3.869636e+07,135.0,23413221.0,45505143.0,8.754595e+07,189502619.0
admission_type_id,101766.0,2.024006e+00,1.445403e+00,1.0,1.0,1.0,3.000000e+00,8.0
discharge_disposition_id,101766.0,3.715642e+00,5.280166e+00,1.0,1.0,1.0,4.000000e+00,28.0
admission_source_id,101766.0,5.754437e+00,4.064081e+00,1.0,1.0,7.0,7.000000e+00,25.0
time_in_hospital,101766.0,4.395987e+00,2.985108e+00,1.0,2.0,4.0,6.000000e+00,14.0
num_lab_procedures,101766.0,4.309564e+01,1.967436e+01,1.0,31.0,44.0,5.700000e+01,132.0
num_procedures,101766.0,1.339730e+00,1.705807e+00,0.0,0.0,1.0,2.000000e+00,6.0
num_medications,101766.0,1.602184e+01,8.127566e+00,1.0,10.0,15.0,2.000000e+01,81.0
number_outpatient,101766.0,3.693572e-01,1.267265e+00,0.0,0.0,0.0,0.000000e+00,42.0
number_emergency,101766.0,1.978362e-01,9.304723e-01,0.0,0.0,0.0,0.000000e+00,76.0
number_inpatient,101766.0,6.355659e-01,1.262863e+00,0.0,0.0,0.0,1.000000e+00,21.0
number_diagnoses,101766.0,7.422607e+00,1.933600e+00,1.0,6.0,8.0,9.000000e+00,16.0

In [19]:
# Check correlations between the numerical clinical features and the binary readmission target
numeric_clinical = [
    "time_in_hospital",
    "num_lab_procedures",
    "num_procedures",
    "num_medications",
    "number_outpatient",
    "number_emergency",
    "number_inpatient",
    "number_diagnoses",
]

correlation_data = X[numeric_clinical].copy()
correlation_data["readmitted"] = y_binary

display(correlation_data.corr()["readmitted"].sort_values(ascending=False))

readmitted            1.000000
number_inpatient      0.165147
number_emergency      0.060747
number_diagnoses      0.049524
time_in_hospital      0.044199
num_medications       0.038432
num_lab_procedures    0.020364
number_outpatient     0.018893
num_procedures       -0.012227
Name: readmitted, dtype: float64

In [20]:
# Examine the categories represented by the admission, discharge, and admission-source IDs
id_categorical_columns = [
    "admission_type_id",
    "discharge_disposition_id",
    "admission_source_id",
]

for column in id_categorical_columns:
    print(f"\n{column}")
    print("Unique values:", sorted(df[column].dropna().unique()))
    print("\nValue counts:")
    print(df[column].value_counts().sort_index())

admission_type_id
Unique values: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)]

Value counts:
admission_type_id
1    53990
2    18480
3    18869
4       10
5     4785
6     5291
7       21
8      320
Name: count, dtype: int64

discharge_disposition_id
Unique values: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(27), np.int64(28)]

Value counts:
discharge_disposition_id
1     60234
2      2128
3     13954
4       815
5      1184
6     12902
7       623
8       108
9        21
10        6
11     1642
12        3
13      399
14      372
15       63
16       11
17       14
18     3691
19        8
20        2
22     1993
23      412
24       48
25      989
27        5
28      139
Name: count, dtype: int64

admission_source_id
Unique values: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(13), np.int64(14), np.int64(17), np.int64(20), np.int64(22), np.int64(25)]

Value counts:
admission_source_id
1     29565
2      1104
3       187
4      3187
5       855
6      2264
7     57494
8        16
9       125
10        8
11        2
13        1
14        2
17     6781
20      161
22       12
25        2
Name: count, dtype: int64

In [21]:
# Identify columns with only one unique value and columns dominated by one value
for column in df.columns:
    unique_count = df[column].nunique(dropna=False)

    if unique_count <= 1:
        print(f"{column}: CONSTANT — {unique_count} unique value")

examide: CONSTANT — 1 unique value
citoglipton: CONSTANT — 1 unique value

In [22]:
# Remove columns that contain only one unique value because they provide no predictive information
constant_columns = ["examide", "citoglipton"]

X_clean = X.drop(columns=constant_columns)

print("Removed columns:", constant_columns)
print("Original feature count:", X.shape[1])
print("Feature count after removal:", X_clean.shape[1])

Removed columns: ['examide', 'citoglipton']
Original feature count: 49
Feature count after removal: 47

In [23]:
# Check how many unique values exist in the encounter and patient identifier columns
print("Total encounters:", len(X_clean))
print("Unique encounter IDs:", X_clean["encounter_id"].nunique())
print("Unique patient IDs:", X_clean["patient_nbr"].nunique())

print("\nEncounter ID duplicated:", X_clean["encounter_id"].duplicated().sum())
print("Patient ID duplicated:", X_clean["patient_nbr"].duplicated().sum())

Total encounters: 101766
Unique encounter IDs: 101766
Unique patient IDs: 71518

Encounter ID duplicated: 0
Patient ID duplicated: 30248

In [24]:
# Split patients into train, validation, and test groups so no patient appears in multiple splits
from sklearn.model_selection import train_test_split

unique_patients = X_clean["patient_nbr"].unique()

train_patients, temp_patients = train_test_split(
    unique_patients,
    test_size=0.20,
    random_state=42,
)

validation_patients, test_patients = train_test_split(
    temp_patients,
    test_size=0.50,
    random_state=42,
)

print("Total unique patients:", len(unique_patients))
print("Training patients:", len(train_patients))
print("Validation patients:", len(validation_patients))
print("Test patients:", len(test_patients))

Total unique patients: 71518
Training patients: 57214
Validation patients: 7152
Test patients: 7152

In [25]:
# Assign every hospital encounter to train, validation, or test based on the patient's ID
train_mask = X_clean["patient_nbr"].isin(train_patients)
validation_mask = X_clean["patient_nbr"].isin(validation_patients)
test_mask = X_clean["patient_nbr"].isin(test_patients)

X_train = X_clean.loc[train_mask].copy()
X_validation = X_clean.loc[validation_mask].copy()
X_test = X_clean.loc[test_mask].copy()

y_train = y_binary.loc[train_mask].copy()
y_validation = y_binary.loc[validation_mask].copy()
y_test = y_binary.loc[test_mask].copy()

print("Training encounters:", len(X_train))
print("Validation encounters:", len(X_validation))
print("Test encounters:", len(X_test))

Training encounters: 81477
Validation encounters: 10113
Test encounters: 10176

In [26]:
# Verify that no patient appears in more than one dataset split
train_patient_set = set(X_train["patient_nbr"])
validation_patient_set = set(X_validation["patient_nbr"])
test_patient_set = set(X_test["patient_nbr"])

print("Train ∩ Validation:", len(train_patient_set & validation_patient_set))
print("Train ∩ Test:", len(train_patient_set & test_patient_set))
print("Validation ∩ Test:", len(validation_patient_set & test_patient_set))

Train ∩ Validation: 0
Train ∩ Test: 0
Validation ∩ Test: 0

In [27]:
# Check whether the 30-day readmission rate is reasonably consistent across all dataset splits
print("Training target distribution:")
print(y_train.value_counts())
print((y_train.value_counts(normalize=True) * 100).round(2))

print("\nValidation target distribution:")
print(y_validation.value_counts())
print((y_validation.value_counts(normalize=True) * 100).round(2))

print("\nTest target distribution:")
print(y_test.value_counts())
print((y_test.value_counts(normalize=True) * 100).round(2))

Training target distribution:
readmitted
0    72289
1     9188
Name: count, dtype: int64
readmitted
0    88.72
1    11.28
Name: proportion, dtype: float64

Validation target distribution:
readmitted
0    9027
1    1086
Name: count, dtype: int64
readmitted
0    89.26
1    10.74
Name: proportion, dtype: float64

Test target distribution:
readmitted
0    9093
1    1083
Name: count, dtype: int64
readmitted
0    89.36
1    10.64
Name: proportion, dtype: float64

In [28]:
# Remove identifiers because they identify patients/encounters rather than represent clinical information
identifier_columns = ["encounter_id", "patient_nbr"]

X_train_model = X_train.drop(columns=identifier_columns)
X_validation_model = X_validation.drop(columns=identifier_columns)
X_test_model = X_test.drop(columns=identifier_columns)

print("Training features:", X_train_model.shape)
print("Validation features:", X_validation_model.shape)
print("Test features:", X_test_model.shape)

Training features: (81477, 45)
Validation features: (10113, 45)
Test features: (10176, 45)

In [29]:
# Analyze readmission outcomes for each discharge disposition category
discharge_analysis = (
    df.groupby("discharge_disposition_id")["readmitted"]
    .value_counts(normalize=True)
    .unstack(fill_value=0)
    .round(3)
)

display(discharge_analysis)

readmitted                  <30    >30     NO
discharge_disposition_id
1                         0.093  0.357  0.550
2                         0.161  0.314  0.525
3                         0.147  0.352  0.501
4                         0.128  0.341  0.531
5                         0.209  0.296  0.496
6                         0.127  0.416  0.457
7                         0.144  0.355  0.501
8                         0.139  0.352  0.509
9                         0.429  0.095  0.476
10                        0.000  0.667  0.333
11                        0.000  0.000  1.000
12                        0.667  0.000  0.333
13                        0.048  0.090  0.862
14                        0.065  0.019  0.917
15                        0.444  0.286  0.270
16                        0.000  0.545  0.455
17                        0.000  0.357  0.643
18                        0.124  0.278  0.597
19                        0.000  0.000  1.000
20                        0.000  0.000  1.000
22                        0.277  0.260  0.463
23                        0.073  0.350  0.578
24                        0.146  0.333  0.521
25                        0.093  0.380  0.527
27                        0.000  0.200  0.800
28                        0.367  0.245  0.388

In [30]:
# Remove encounters whose discharge disposition does not represent a normal readmission-eligible discharge
non_readmittable_dispositions = [11, 13, 14, 19, 20, 21]

train_valid_mask = ~X_train_model["discharge_disposition_id"].isin(
    non_readmittable_dispositions
)
validation_valid_mask = ~X_validation_model["discharge_disposition_id"].isin(
    non_readmittable_dispositions
)
test_valid_mask = ~X_test_model["discharge_disposition_id"].isin(
    non_readmittable_dispositions
)

X_train_model = X_train_model.loc[train_valid_mask].copy()
y_train = y_train.loc[X_train_model.index].copy()

X_validation_model = X_validation_model.loc[validation_valid_mask].copy()
y_validation = y_validation.loc[X_validation_model.index].copy()

X_test_model = X_test_model.loc[test_valid_mask].copy()
y_test = y_test.loc[X_test_model.index].copy()

print("Training encounters after filtering:", len(X_train_model))
print("Validation encounters after filtering:", len(X_validation_model))
print("Test encounters after filtering:", len(X_test_model))

Training encounters after filtering: 79527
Validation encounters after filtering: 9894
Test encounters after filtering: 9922

In [31]:
# Verify that filtering did not introduce any patient overlap between the dataset splits
train_patients_after_filter = set(X_train.loc[X_train_model.index, "patient_nbr"])
validation_patients_after_filter = set(
    X_validation.loc[X_validation_model.index, "patient_nbr"]
)
test_patients_after_filter = set(X_test.loc[X_test_model.index, "patient_nbr"])

print("Train ∩ Validation:", len(
    train_patients_after_filter & validation_patients_after_filter
))
print("Train ∩ Test:", len(
    train_patients_after_filter & test_patients_after_filter
))
print("Validation ∩ Test:", len(
    validation_patients_after_filter & test_patients_after_filter
))

Train ∩ Validation: 0
Train ∩ Test: 0
Validation ∩ Test: 0

In [32]:
# Check missing values in the training features after removing invalid discharge dispositions
missing_train = (
    X_train_model.isna()
    .sum()
    .sort_values(ascending=False)
)

missing_train_percentage = (
    X_train_model.isna()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

missing_summary = pd.DataFrame({
    "missing_count": missing_train,
    "missing_percentage": missing_train_percentage.round(2)
})

display(missing_summary[missing_summary["missing_count"] > 0])

                   missing_count  missing_percentage
weight                     77048               96.88
max_glu_serum              75381               94.79
A1Cresult                  66059               83.06
medical_specialty          38943               48.97
payer_code                 31533               39.65
race                        1767                2.22
diag_3                      1133                1.42
diag_2                       277                0.35
diag_1                        14                0.02

In [33]:
# Remove features with excessive missingness or limited usefulness before model preprocessing
high_missing_columns = ["weight", "payer_code"]

X_train_model = X_train_model.drop(columns=high_missing_columns)
X_validation_model = X_validation_model.drop(columns=high_missing_columns)
X_test_model = X_test_model.drop(columns=high_missing_columns)

print("Dropped columns:", high_missing_columns)
print("Training features remaining:", X_train_model.shape[1])
print("Validation features remaining:", X_validation_model.shape[1])
print("Test features remaining:", X_test_model.shape[1])

Dropped columns: ['weight', 'payer_code']
Training features remaining: 43
Validation features remaining: 43
Test features remaining: 43

In [34]:
# Normalize ICD-9 diagnosis codes to their three-digit category for consistent categorical encoding
diagnosis_columns = ["diag_1", "diag_2", "diag_3"]

for column in diagnosis_columns:
    X_train_model[column] = (
        X_train_model[column]
        .astype("string")
        .str.strip()
        .str[:3]
    )

    X_validation_model[column] = (
        X_validation_model[column]
        .astype("string")
        .str.strip()
        .str[:3]
    )

    X_test_model[column] = (
        X_test_model[column]
        .astype("string")
        .str.strip()
        .str[:3]
    )

print("Diagnosis columns cleaned:")
for column in diagnosis_columns:
    print(f"{column}: {X_train_model[column].nunique(dropna=True)} unique categories")

Diagnosis columns cleaned:
diag_1: 662 unique categories
diag_2: 640 unique categories
diag_3: 662 unique categories

In [35]:
# Define which features are categorical and which are truly numerical for the ML pipeline
categorical_columns = [
    "race",
    "gender",
    "age",
    "admission_type_id",
    "discharge_disposition_id",
    "admission_source_id",
    "medical_specialty",
    "diag_1",
    "diag_2",
    "diag_3",
    "max_glu_serum",
    "A1Cresult",
    "metformin",
    "repaglinide",
    "nateglinide",
    "chlorpropamide",
    "glimepiride",
    "acetohexamide",
    "glipizide",
    "glyburide",
    "tolbutamide",
    "pioglitazone",
    "rosiglitazone",
    "acarbose",
    "miglitol",
    "troglitazone",
    "tolazamide",
    "insulin",
    "glyburide-metformin",
    "glipizide-metformin",
    "glimepiride-pioglitazone",
    "metformin-rosiglitazone",
    "metformin-pioglitazone",
    "change",
    "diabetesMed",
]

numerical_columns = [
    "time_in_hospital",
    "num_lab_procedures",
    "num_procedures",
    "num_medications",
    "number_outpatient",
    "number_emergency",
    "number_inpatient",
    "number_diagnoses",
]

print("Number of categorical features:", len(categorical_columns))
print("Number of numerical features:", len(numerical_columns))
print("Total input features:", len(categorical_columns) + len(numerical_columns))

print("\nMissing categorical columns:")
print(set(categorical_columns) - set(X_train_model.columns))

print("\nMissing numerical columns:")
print(set(numerical_columns) - set(X_train_model.columns))

Number of categorical features: 35
Number of numerical features: 8
Total input features: 43

Missing categorical columns:
set()

Missing numerical columns:
set()

In [36]:
# Build leakage-safe preprocessing pipelines for numerical and categorical features
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

numeric_pipeline = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
    ]
)

categorical_pipeline = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="constant", fill_value="Missing")),
        ("encoder", OneHotEncoder(handle_unknown="ignore")),
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("numeric", numeric_pipeline, numerical_columns),
        ("categorical", categorical_pipeline, categorical_columns),
    ]
)

print("Preprocessing pipeline created successfully.")
print("Numerical preprocessing: median imputation + standardization")
print("Categorical preprocessing: missing-value handling + one-hot encoding")

Preprocessing pipeline created successfully.
Numerical preprocessing: median imputation + standardization
Categorical preprocessing: missing-value handling + one-hot encoding

In [37]:
# Convert categorical missing values to NumPy NaN so scikit-learn can process them safely
for data in [X_train_model, X_validation_model, X_test_model]:
    data[categorical_columns] = (
        data[categorical_columns]
        .astype(object)
        .where(data[categorical_columns].notna(), np.nan)
    )

# Fit preprocessing only on the training data and apply the same transformation to validation and test data
X_train_processed = preprocessor.fit_transform(X_train_model)

X_validation_processed = preprocessor.transform(X_validation_model)

X_test_processed = preprocessor.transform(X_test_model)

print("Training processed shape:", X_train_processed.shape)
print("Validation processed shape:", X_validation_processed.shape)
print("Test processed shape:", X_test_processed.shape)

Training processed shape: (79527, 2189)
Validation processed shape: (9894, 2189)
Test processed shape: (9922, 2189)

In [38]:
# Calculate the class imbalance using training data only
negative_count = (y_train == 0).sum()
positive_count = (y_train == 1).sum()

scale_pos_weight = negative_count / positive_count

print("Training class distribution:")
print("Not readmitted (0):", negative_count)
print("Readmitted within 30 days (1):", positive_count)

print("\nPositive class percentage:",
      round((positive_count / len(y_train)) * 100, 2), "%")

print("Negative class percentage:",
      round((negative_count / len(y_train)) * 100, 2), "%")

print("\nXGBoost scale_pos_weight:",
      round(scale_pos_weight, 4))

Training class distribution:
Not readmitted (0): 70372
Readmitted within 30 days (1): 9155

Positive class percentage: 11.51 %
Negative class percentage: 88.49 %

XGBoost scale_pos_weight: 7.6867

In [39]:
# Import the classification models and metrics required to evaluate our readmission prediction system
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
)
from xgboost import XGBClassifier

print("ML models and evaluation metrics imported successfully.")

ML models and evaluation metrics imported successfully.

In [40]:
# Train Logistic Regression as the baseline model for 30-day readmission prediction
logistic_model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    random_state=42,
)

logistic_model.fit(X_train_processed, y_train)

print("Logistic Regression trained successfully.")

Logistic Regression trained successfully.

In [41]:
# Evaluate Logistic Regression using the project's required classification metrics
logistic_pred = logistic_model.predict(X_validation_processed)
logistic_proba = logistic_model.predict_proba(X_validation_processed)[:, 1]

logistic_metrics = {
    "accuracy": accuracy_score(y_validation, logistic_pred),
    "precision": precision_score(y_validation, logistic_pred, zero_division=0),
    "recall": recall_score(y_validation, logistic_pred, zero_division=0),
    "f1": f1_score(y_validation, logistic_pred, zero_division=0),
    "roc_auc": roc_auc_score(y_validation, logistic_proba),
}

print("Logistic Regression — Validation Results")
for metric, value in logistic_metrics.items():
    print(f"{metric.upper():10}: {value:.4f}")

Logistic Regression — Validation Results
ACCURACY  : 0.6668
PRECISION : 0.1754
RECALL    : 0.5551
F1        : 0.2665
ROC_AUC   : 0.6645

In [42]:
# Train Random Forest to capture nonlinear relationships between patient and hospital features
random_forest_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_leaf=2,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1,
)

random_forest_model.fit(X_train_processed, y_train)

print("Random Forest trained successfully.")

Random Forest trained successfully.

In [43]:
# Evaluate Random Forest on the validation set using the same metrics as Logistic Regression
random_forest_pred = random_forest_model.predict(X_validation_processed)
random_forest_proba = random_forest_model.predict_proba(X_validation_processed)[:, 1]

random_forest_metrics = {
    "accuracy": accuracy_score(y_validation, random_forest_pred),
    "precision": precision_score(y_validation, random_forest_pred, zero_division=0),
    "recall": recall_score(y_validation, random_forest_pred, zero_division=0),
    "f1": f1_score(y_validation, random_forest_pred, zero_division=0),
    "roc_auc": roc_auc_score(y_validation, random_forest_proba),
}

print("Random Forest — Validation Results")
for metric, value in random_forest_metrics.items():
    print(f"{metric.upper():10}: {value:.4f}")

Random Forest — Validation Results
ACCURACY  : 0.8597
PRECISION : 0.3071
RECALL    : 0.2280
F1        : 0.2617
ROC_AUC   : 0.6975

In [44]:
# Train XGBoost with class weighting to handle the imbalanced readmission target
xgboost_model = XGBClassifier(
    n_estimators=300,
    max_depth=4,
    learning_rate=0.05,
    min_child_weight=5,
    subsample=0.7,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,
    n_jobs=-1,
)

xgboost_model.fit(X_train_processed, y_train)

print("XGBoost trained successfully.")

XGBoost trained successfully.

In [45]:
# Evaluate XGBoost on the validation set using the same required metrics
xgboost_pred = xgboost_model.predict(X_validation_processed)
xgboost_proba = xgboost_model.predict_proba(X_validation_processed)[:, 1]

xgboost_metrics = {
    "accuracy": accuracy_score(y_validation, xgboost_pred),
    "precision": precision_score(y_validation, xgboost_pred, zero_division=0),
    "recall": recall_score(y_validation, xgboost_pred, zero_division=0),
    "f1": f1_score(y_validation, xgboost_pred, zero_division=0),
    "roc_auc": roc_auc_score(y_validation, xgboost_proba),
}

print("XGBoost — Validation Results")
for metric, value in xgboost_metrics.items():
    print(f"{metric.upper():10}: {value:.4f}")

XGBoost — Validation Results
ACCURACY  : 0.6670
PRECISION : 0.1874
RECALL    : 0.6154
F1        : 0.2873
ROC_AUC   : 0.6923

In [46]:
# Compare all trained models using the same validation metrics
model_comparison = pd.DataFrame(
    [logistic_metrics, random_forest_metrics, xgboost_metrics],
    index=["Logistic Regression", "Random Forest", "XGBoost"],
)

display(model_comparison.round(4))

                     accuracy  precision  recall      f1  roc_auc
Logistic Regression    0.6668     0.1754  0.5551  0.2665   0.6645
Random Forest          0.8597     0.3071  0.2280  0.2617   0.6975
XGBoost                0.6670     0.1874  0.6154  0.2873   0.6923

In [47]:
# Import TensorFlow and prepare the neural network training environment
import tensorflow as tf

print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.20.0

In [48]:
# Convert the sparse one-hot encoded features to dense arrays for TensorFlow
X_train_dl = X_train_processed.toarray()
X_validation_dl = X_validation_processed.toarray()

print("Training data shape:", X_train_dl.shape)
print("Validation data shape:", X_validation_dl.shape)
print("Training data type:", X_train_dl.dtype)

Training data shape: (79527, 2189)
Validation data shape: (9894, 2189)
Training data type: float64

In [49]:
# Calculate class weights so the neural network gives more importance to readmitted patients
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

classes = np.unique(y_train)

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=y_train,
)

class_weight_dict = dict(zip(classes, class_weights))

print("Class weights:")
print("Class 0:", round(class_weight_dict[0], 4))
print("Class 1:", round(class_weight_dict[1], 4))

Class weights:
Class 0: 0.565
Class 1: 4.3434

In [50]:
# Build a feed-forward neural network for 30-day hospital readmission prediction
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input

neural_network = Sequential([
    Input(shape=(X_train_dl.shape[1],)),

    Dense(128, activation="relu"),
    Dropout(0.30),

    Dense(64, activation="relu"),
    Dropout(0.20),

    Dense(1, activation="sigmoid"),
])

neural_network.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=[
        tf.keras.metrics.BinaryAccuracy(name="accuracy"),
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall"),
        tf.keras.metrics.AUC(name="roc_auc"),
    ],
)

neural_network.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │       280,320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 288,641 (1.10 MB)

 Trainable params: 288,641 (1.10 MB)

 Non-trainable params: 0 (0.00 B)

In [51]:
# Train the neural network with class weighting and early stopping to prevent overfitting
from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(
    monitor="val_roc_auc",
    mode="max",
    patience=5,
    restore_best_weights=True,
    verbose=1,
)

history = neural_network.fit(
    X_train_dl,
    y_train,
    validation_data=(X_validation_dl, y_validation),
    epochs=30,
    batch_size=256,
    class_weight=class_weight_dict,
    callbacks=[early_stopping],
    verbose=1,
)

print("Neural network training completed.")

Epoch 1/30
311/311 ━━━━━━━━━━━━━━━━━━━━ 9s 24ms/step - accuracy: 0.6087 - loss: 0.6611 - precision: 0.1638 - recall: 0.5843 - roc_auc: 0.6411 - val_accuracy: 0.5528 - val_loss: 0.6798 - val_precision: 0.1601 - val_recall: 0.7303 - val_roc_auc: 0.6889
Epoch 2/30
311/311 ━━━━━━━━━━━━━━━━━━━━ 6s 19ms/step - accuracy: 0.6175 - loss: 0.6433 - precision: 0.1767 - recall: 0.6350 - roc_auc: 0.6760 - val_accuracy: 0.6367 - val_loss: 0.6179 - val_precision: 0.1776 - val_recall: 0.6423 - val_roc_auc: 0.6901
Epoch 3/30
311/311 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.6139 - loss: 0.6340 - precision: 0.1797 - recall: 0.6605 - roc_auc: 0.6901 - val_accuracy: 0.6554 - val_loss: 0.5961 - val_precision: 0.1799 - val_recall: 0.6070 - val_roc_auc: 0.6894
Epoch 4/30
311/311 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - accuracy: 0.6176 - loss: 0.6245 - precision: 0.1841 - recall: 0.6764 - roc_auc: 0.7036 - val_accuracy: 0.6917 - val_loss: 0.5788 - val_precision: 0.1900 - val_recall: 0.5598 - val_roc_auc: 0.6873
Epoch 5/30
311/311 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - accuracy: 0.6298 - loss: 0.6127 - precision: 0.1920 - recall: 0.6904 - roc_auc: 0.7200 - val_accuracy: 0.6053 - val_loss: 0.6382 - val_precision: 0.1658 - val_recall: 0.6497 - val_roc_auc: 0.6793
Epoch 6/30
311/311 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.6363 - loss: 0.5992 - precision: 0.1996 - recall: 0.7170 - roc_auc: 0.7366 - val_accuracy: 0.7092 - val_loss: 0.5502 - val_precision: 0.1955 - val_recall: 0.5348 - val_roc_auc: 0.6806
Epoch 7/30
311/311 ━━━━━━━━━━━━━━━━━━━━ 7s 18ms/step - accuracy: 0.6526 - loss: 0.5830 - precision: 0.2089 - recall: 0.7238 - roc_auc: 0.7545 - val_accuracy: 0.6502 - val_loss: 0.5924 - val_precision: 0.1795 - val_recall: 0.6182 - val_roc_auc: 0.6792
Epoch 7: early stopping
Restoring model weights from the end of the best epoch: 2.
Neural network training completed.

In [52]:
# Evaluate the trained neural network on the validation set using the same five project metrics
neural_network_proba = neural_network.predict(
    X_validation_dl,
    verbose=0
).ravel()

neural_network_pred = (neural_network_proba >= 0.50).astype(int)

neural_network_metrics = {
    "accuracy": accuracy_score(y_validation, neural_network_pred),
    "precision": precision_score(
        y_validation,
        neural_network_pred,
        zero_division=0,
    ),
    "recall": recall_score(
        y_validation,
        neural_network_pred,
        zero_division=0,
    ),
    "f1": f1_score(
        y_validation,
        neural_network_pred,
        zero_division=0,
    ),
    "roc_auc": roc_auc_score(
        y_validation,
        neural_network_proba,
    ),
}

print("Neural Network — Validation Results")

for metric, value in neural_network_metrics.items():
    print(f"{metric.upper():10}: {value:.4f}")

Neural Network — Validation Results
ACCURACY  : 0.6367
PRECISION : 0.1776
RECALL    : 0.6423
F1        : 0.2783
ROC_AUC   : 0.6900

In [53]:
# Compare all four models using the same validation metrics
model_comparison = pd.DataFrame(
    [
        logistic_metrics,
        random_forest_metrics,
        xgboost_metrics,
        neural_network_metrics,
    ],
    index=[
        "Logistic Regression",
        "Random Forest",
        "XGBoost",
        "Neural Network",
    ],
)

display(model_comparison.round(4))

                     accuracy  precision  recall      f1  roc_auc
Logistic Regression    0.6668     0.1754  0.5551  0.2665   0.6645
Random Forest          0.8597     0.3071  0.2280  0.2617   0.6975
XGBoost                0.6670     0.1874  0.6154  0.2873   0.6923
Neural Network         0.6367     0.1776  0.6423  0.2783   0.6900

In [54]:
# Check how different probability thresholds change XGBoost precision, recall, and F1
thresholds = np.arange(0.10, 0.51, 0.05)

threshold_results = []

for threshold in thresholds:
    predictions = (xgboost_proba >= threshold).astype(int)

    threshold_results.append({
        "threshold": threshold,
        "precision": precision_score(
            y_validation,
            predictions,
            zero_division=0,
        ),
        "recall": recall_score(
            y_validation,
            predictions,
            zero_division=0,
        ),
        "f1": f1_score(
            y_validation,
            predictions,
            zero_division=0,
        ),
    })

xgb_threshold_results = pd.DataFrame(threshold_results)

display(xgb_threshold_results.round(4))

   threshold  precision  recall      f1
0       0.10     0.1091  1.0000  0.1967
1       0.15     0.1092  1.0000  0.1970
2       0.20     0.1102  0.9981  0.1985
3       0.25     0.1128  0.9880  0.2025
4       0.30     0.1188  0.9583  0.2114
5       0.35     0.1302  0.9147  0.2280
6       0.40     0.1418  0.8156  0.2417
7       0.45     0.1603  0.7183  0.2620
8       0.50     0.1874  0.6154  0.2873

In [55]:
# Perform a finer threshold search to find the XGBoost threshold with the best F1 score
fine_thresholds = np.arange(0.30, 0.71, 0.01)

fine_results = []

for threshold in fine_thresholds:
    predictions = (xgboost_proba >= threshold).astype(int)

    fine_results.append({
        "threshold": threshold,
        "precision": precision_score(
            y_validation,
            predictions,
            zero_division=0,
        ),
        "recall": recall_score(
            y_validation,
            predictions,
            zero_division=0,
        ),
        "f1": f1_score(
            y_validation,
            predictions,
            zero_division=0,
        ),
    })

xgb_fine_threshold_results = pd.DataFrame(fine_results)

best_threshold_row = xgb_fine_threshold_results.loc[
    xgb_fine_threshold_results["f1"].idxmax()
]

print("Best threshold based on validation F1:")
print(best_threshold_row)

display(xgb_fine_threshold_results.round(4))

Best threshold based on validation F1:
threshold    0.530000
precision    0.208410
recall       0.528267
f1           0.298899
Name: 23, dtype: float64

    threshold  precision  recall      f1
0        0.30     0.1188  0.9583  0.2114
1        0.31     0.1207  0.9518  0.2142
2        0.32     0.1224  0.9398  0.2166
3        0.33     0.1255  0.9370  0.2214
4        0.34     0.1276  0.9231  0.2242
5        0.35     0.1302  0.9147  0.2280
6        0.36     0.1321  0.8943  0.2302
7        0.37     0.1340  0.8730  0.2323
8        0.38     0.1368  0.8554  0.2359
9        0.39     0.1394  0.8378  0.2391
10       0.40     0.1418  0.8156  0.2417
11       0.41     0.1449  0.7952  0.2452
12       0.42     0.1482  0.7785  0.2490
13       0.43     0.1505  0.7544  0.2510
14       0.44     0.1559  0.7405  0.2576
15       0.45     0.1603  0.7183  0.2620
16       0.46     0.1656  0.7006  0.2679
17       0.47     0.1712  0.6803  0.2736
18       0.48     0.1770  0.6608  0.2792
19       0.49     0.1814  0.6376  0.2825
20       0.50     0.1874  0.6154  0.2873
21       0.51     0.1964  0.5904  0.2947
22       0.52     0.1989  0.5551  0.2929
23       0.53     0.2084  0.5283  0.2989
24       0.54     0.2135  0.4912  0.2976
25       0.55     0.2154  0.4560  0.2926
26       0.56     0.2231  0.4337  0.2946
27       0.57     0.2292  0.4059  0.2930
28       0.58     0.2394  0.3865  0.2956
29       0.59     0.2492  0.3679  0.2972
30       0.60     0.2523  0.3355  0.2880
31       0.61     0.2589  0.3105  0.2823
32       0.62     0.2687  0.2929  0.2803
33       0.63     0.2778  0.2753  0.2765
34       0.64     0.2890  0.2539  0.2704
35       0.65     0.3055  0.2373  0.2671
36       0.66     0.3192  0.2169  0.2583
37       0.67     0.3313  0.1983  0.2481
38       0.68     0.3438  0.1826  0.2385
39       0.69     0.3740  0.1733  0.2369
40       0.70     0.3822  0.1548  0.2203

In [56]:
# Evaluate XGBoost at the selected validation threshold of 0.53
selected_threshold = 0.53

xgb_selected_pred = (
    xgboost_proba >= selected_threshold
).astype(int)

xgb_selected_metrics = {
    "accuracy": accuracy_score(
        y_validation,
        xgb_selected_pred,
    ),
    "precision": precision_score(
        y_validation,
        xgb_selected_pred,
        zero_division=0,
    ),
    "recall": recall_score(
        y_validation,
        xgb_selected_pred,
        zero_division=0,
    ),
    "f1": f1_score(
        y_validation,
        xgb_selected_pred,
        zero_division=0,
    ),
    "roc_auc": roc_auc_score(
        y_validation,
        xgboost_proba,
    ),
}

print("XGBoost — Validation Performance at Threshold 0.53")

for metric, value in xgb_selected_metrics.items():
    print(f"{metric.upper():10}: {value:.4f}")

XGBoost — Validation Performance at Threshold 0.53
ACCURACY  : 0.7297
PRECISION : 0.2084
RECALL    : 0.5283
F1        : 0.2989
ROC_AUC   : 0.6923

In [57]:
# Show the confusion matrix to understand correct predictions and false alarms
from sklearn.metrics import confusion_matrix

xgb_confusion = confusion_matrix(
    y_validation,
    xgb_selected_pred,
)

tn, fp, fn, tp = xgb_confusion.ravel()

print("XGBoost Confusion Matrix — Threshold 0.53")
print()
print("True Negatives :", tn)
print("False Positives:", fp)
print("False Negatives:", fn)
print("True Positives :", tp)

XGBoost Confusion Matrix — Threshold 0.53

True Negatives : 6650
False Positives: 2165
False Negatives: 509
True Positives : 570

In [58]:
# Analyze how different probability thresholds affect Neural Network precision, recall, and F1
nn_thresholds = np.arange(0.30, 0.71, 0.01)

nn_threshold_results = []

for threshold in nn_thresholds:
    predictions = (neural_network_proba >= threshold).astype(int)

    nn_threshold_results.append({
        "threshold": threshold,
        "precision": precision_score(
            y_validation,
            predictions,
            zero_division=0,
        ),
        "recall": recall_score(
            y_validation,
            predictions,
            zero_division=0,
        ),
        "f1": f1_score(
            y_validation,
            predictions,
            zero_division=0,
        ),
    })

nn_threshold_results = pd.DataFrame(nn_threshold_results)

best_nn_threshold_row = nn_threshold_results.loc[
    nn_threshold_results["f1"].idxmax()
]

print("Best Neural Network threshold based on validation F1:")
print(best_nn_threshold_row)

display(nn_threshold_results.round(4))

Best Neural Network threshold based on validation F1:
threshold    0.570000
precision    0.219810
recall       0.450417
f1           0.295441
Name: 27, dtype: float64

    threshold  precision  recall      f1
0        0.30     0.1234  0.9296  0.2179
1        0.31     0.1256  0.9231  0.2211
2        0.32     0.1276  0.9157  0.2239
3        0.33     0.1290  0.9027  0.2257
4        0.34     0.1311  0.8953  0.2287
5        0.35     0.1336  0.8869  0.2322
6        0.36     0.1356  0.8758  0.2349
7        0.37     0.1379  0.8619  0.2378
8        0.38     0.1401  0.8471  0.2404
9        0.39     0.1425  0.8350  0.2434
10       0.40     0.1447  0.8174  0.2458
11       0.41     0.1480  0.8054  0.2501
12       0.42     0.1502  0.7868  0.2522
13       0.43     0.1515  0.7646  0.2529
14       0.44     0.1550  0.7507  0.2569
15       0.45     0.1579  0.7312  0.2597
16       0.46     0.1606  0.7155  0.2624
17       0.47     0.1642  0.6960  0.2657
18       0.48     0.1678  0.6756  0.2689
19       0.49     0.1726  0.6599  0.2736
20       0.50     0.1776  0.6423  0.2783
21       0.51     0.1829  0.6219  0.2826
22       0.52     0.1884  0.5987  0.2867
23       0.53     0.1931  0.5681  0.2882
24       0.54     0.1961  0.5348  0.2870
25       0.55     0.2004  0.5005  0.2862
26       0.56     0.2091  0.4745  0.2902
27       0.57     0.2198  0.4504  0.2954
28       0.58     0.2266  0.4217  0.2948
29       0.59     0.2345  0.3883  0.2924
30       0.60     0.2476  0.3605  0.2936
31       0.61     0.2543  0.3262  0.2858
32       0.62     0.2661  0.3021  0.2830
33       0.63     0.2768  0.2678  0.2723
34       0.64     0.2910  0.2465  0.2669
35       0.65     0.2916  0.2178  0.2493
36       0.66     0.3040  0.2020  0.2428
37       0.67     0.3077  0.1816  0.2284
38       0.68     0.3315  0.1715  0.2260
39       0.69     0.3514  0.1566  0.2167
40       0.70     0.3695  0.1390  0.2020

In [59]:
# Evaluate the selected XGBoost model on the untouched test set using the validation-selected threshold
xgboost_test_proba = xgboost_model.predict_proba(
    X_test_processed
)[:, 1]

xgboost_test_pred = (
    xgboost_test_proba >= 0.53
).astype(int)

xgboost_test_metrics = {
    "accuracy": accuracy_score(
        y_test,
        xgboost_test_pred,
    ),
    "precision": precision_score(
        y_test,
        xgboost_test_pred,
        zero_division=0,
    ),
    "recall": recall_score(
        y_test,
        xgboost_test_pred,
        zero_division=0,
    ),
    "f1": f1_score(
        y_test,
        xgboost_test_pred,
        zero_division=0,
    ),
    "roc_auc": roc_auc_score(
        y_test,
        xgboost_test_proba,
    ),
}

print("XGBoost — Final Test Results")
print("Threshold:", 0.53)

for metric, value in xgboost_test_metrics.items():
    print(f"{metric.upper():10}: {value:.4f}")

XGBoost — Final Test Results
Threshold: 0.53
ACCURACY  : 0.7154
PRECISION : 0.1934
RECALL    : 0.5093
F1        : 0.2803
ROC_AUC   : 0.6708

In [60]:
# Convert the processed test features to a dense NumPy array for TensorFlow
X_test_dl = X_test_processed.toarray().astype("float32")

print("Test data shape:", X_test_dl.shape)
print("Test data type:", X_test_dl.dtype)

Test data shape: (9922, 2189)
Test data type: float32

In [61]:
# Evaluate the Neural Network on the untouched test set using its validation-selected threshold of 0.60
neural_network_test_proba = neural_network.predict(
    X_test_dl,
    verbose=0
).ravel()

neural_network_test_pred = (
    neural_network_test_proba >= 0.60
).astype(int)

neural_network_test_metrics = {
    "accuracy": accuracy_score(
        y_test,
        neural_network_test_pred,
    ),
    "precision": precision_score(
        y_test,
        neural_network_test_pred,
        zero_division=0,
    ),
    "recall": recall_score(
        y_test,
        neural_network_test_pred,
        zero_division=0,
    ),
    "f1": f1_score(
        y_test,
        neural_network_test_pred,
        zero_division=0,
    ),
    "roc_auc": roc_auc_score(
        y_test,
        neural_network_test_proba,
    ),
}

print("Neural Network — Final Test Results")
print("Threshold:", 0.60)

for metric, value in neural_network_test_metrics.items():
    print(f"{metric.upper():10}: {value:.4f}")

Neural Network — Final Test Results
Threshold: 0.6
ACCURACY  : 0.8026
PRECISION : 0.2295
RECALL    : 0.3454
F1        : 0.2758
ROC_AUC   : 0.6666

In [62]:
# Tune XGBoost hyperparameters using training data and select the best model using validation ROC-AUC
from xgboost import XGBClassifier
from sklearn.metrics import roc_auc_score

xgb_tuning_configs = [
    {
        "n_estimators": 300,
        "max_depth": 3,
        "learning_rate": 0.05,
        "min_child_weight": 3,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
    },
    {
        "n_estimators": 400,
        "max_depth": 3,
        "learning_rate": 0.03,
        "min_child_weight": 3,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
    },
    {
        "n_estimators": 300,
        "max_depth": 4,
        "learning_rate": 0.05,
        "min_child_weight": 5,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
    },
    {
        "n_estimators": 400,
        "max_depth": 4,
        "learning_rate": 0.03,
        "min_child_weight": 5,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
    },
    {
        "n_estimators": 300,
        "max_depth": 5,
        "learning_rate": 0.05,
        "min_child_weight": 5,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
    },
    {
        "n_estimators": 400,
        "max_depth": 5,
        "learning_rate": 0.03,
        "min_child_weight": 5,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
    },
]

tuning_results = []

best_xgb_model = None
best_xgb_proba = None
best_xgb_roc_auc = -1
best_xgb_config = None

for config_number, config in enumerate(xgb_tuning_configs, start=1):

    model = XGBClassifier(
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=42,
        n_jobs=-1,
        scale_pos_weight=scale_pos_weight,
        **config,
    )

    model.fit(X_train_processed, y_train)

    validation_proba = model.predict_proba(
        X_validation_processed
    )[:, 1]

    validation_roc_auc = roc_auc_score(
        y_validation,
        validation_proba,
    )

    tuning_results.append({
        "configuration": config_number,
        **config,
        "validation_roc_auc": validation_roc_auc,
    })

    print(
        f"Configuration {config_number}: "
        f"Validation ROC-AUC = {validation_roc_auc:.4f}"
    )

    if validation_roc_auc > best_xgb_roc_auc:
        best_xgb_roc_auc = validation_roc_auc
        best_xgb_model = model
        best_xgb_proba = validation_proba
        best_xgb_config = config

xgb_tuning_results = pd.DataFrame(tuning_results)

print("\nBest XGBoost configuration:")
print(best_xgb_config)
print(f"Best validation ROC-AUC: {best_xgb_roc_auc:.4f}")

display(xgb_tuning_results.round(4))

Configuration 1: Validation ROC-AUC = 0.6915
Configuration 2: Validation ROC-AUC = 0.6918
Configuration 3: Validation ROC-AUC = 0.6926
Configuration 4: Validation ROC-AUC = 0.6946
Configuration 5: Validation ROC-AUC = 0.6931
Configuration 6: Validation ROC-AUC = 0.6955

Best XGBoost configuration:
{'n_estimators': 400, 'max_depth': 5, 'learning_rate': 0.03, 'min_child_weight': 5, 'subsample': 0.8, 'colsample_bytree': 0.8}
Best validation ROC-AUC: 0.6955

,configuration,n_estimators,max_depth,learning_rate,min_child_weight,subsample,colsample_bytree,validation_roc_auc
0,1,300,3,0.05,3,0.8,0.8,0.6915
1,2,400,3,0.03,3,0.8,0.8,0.6918
2,3,300,4,0.05,5,0.8,0.8,0.6926
3,4,400,4,0.03,5,0.8,0.8,0.6946
4,5,300,5,0.05,5,0.8,0.8,0.6931
5,6,400,5,0.03,5,0.8,0.8,0.6955

In [63]:
# Find the best decision threshold for the tuned XGBoost using validation F1
tuned_thresholds = np.arange(0.30, 0.71, 0.01)

tuned_threshold_results = []

for threshold in tuned_thresholds:
    predictions = (
        best_xgb_proba >= threshold
    ).astype(int)

    tuned_threshold_results.append({
        "threshold": threshold,
        "precision": precision_score(
            y_validation,
            predictions,
            zero_division=0,
        ),
        "recall": recall_score(
            y_validation,
            predictions,
            zero_division=0,
        ),
        "f1": f1_score(
            y_validation,
            predictions,
            zero_division=0,
        ),
    })

tuned_threshold_results = pd.DataFrame(
    tuned_threshold_results
)

best_tuned_threshold_row = tuned_threshold_results.loc[
    tuned_threshold_results["f1"].idxmax()
]

print("Best threshold for tuned XGBoost:")
print(best_tuned_threshold_row)

display(
    tuned_threshold_results.round(4)
)

Best threshold for tuned XGBoost:
threshold    0.520000
precision    0.206054
recall       0.555144
f1           0.300552
Name: 22, dtype: float64

    threshold  precision  recall      f1
0        0.30     0.1183  0.9509  0.2104
1        0.31     0.1206  0.9462  0.2140
2        0.32     0.1227  0.9398  0.2171
3        0.33     0.1246  0.9259  0.2197
4        0.34     0.1276  0.9194  0.2240
5        0.35     0.1295  0.9018  0.2265
6        0.36     0.1321  0.8869  0.2299
7        0.37     0.1358  0.8777  0.2352
8        0.38     0.1385  0.8601  0.2386
9        0.39     0.1413  0.8406  0.2419
10       0.40     0.1436  0.8184  0.2444
11       0.41     0.1470  0.8035  0.2486
12       0.42     0.1505  0.7850  0.2525
13       0.43     0.1541  0.7646  0.2565
14       0.44     0.1577  0.7451  0.2603
15       0.45     0.1638  0.7322  0.2677
16       0.46     0.1683  0.7071  0.2719
17       0.47     0.1737  0.6858  0.2773
18       0.48     0.1797  0.6645  0.2829
19       0.49     0.1847  0.6367  0.2864
20       0.50     0.1901  0.6070  0.2895
21       0.51     0.1979  0.5829  0.2954
22       0.52     0.2061  0.5551  0.3006
23       0.53     0.2090  0.5162  0.2975
24       0.54     0.2153  0.4847  0.2982
25       0.55     0.2205  0.4551  0.2970
26       0.56     0.2265  0.4272  0.2961
27       0.57     0.2354  0.4059  0.2980
28       0.58     0.2394  0.3707  0.2909
29       0.59     0.2507  0.3485  0.2916
30       0.60     0.2578  0.3281  0.2887
31       0.61     0.2661  0.3095  0.2862
32       0.62     0.2770  0.2901  0.2834
33       0.63     0.2899  0.2725  0.2809
34       0.64     0.3039  0.2521  0.2756
35       0.65     0.3178  0.2271  0.2649
36       0.66     0.3230  0.2020  0.2486
37       0.67     0.3413  0.1854  0.2402
38       0.68     0.3617  0.1696  0.2309
39       0.69     0.3848  0.1548  0.2208
40       0.70     0.3862  0.1399  0.2054

In [64]:
# Evaluate the tuned XGBoost on the untouched test set using the validation-selected threshold of 0.52
tuned_xgb_test_proba = best_xgb_model.predict_proba(
    X_test_processed
)[:, 1]

tuned_xgb_test_pred = (
    tuned_xgb_test_proba >= 0.52
).astype(int)

tuned_xgb_test_metrics = {
    "accuracy": accuracy_score(
        y_test,
        tuned_xgb_test_pred,
    ),
    "precision": precision_score(
        y_test,
        tuned_xgb_test_pred,
        zero_division=0,
    ),
    "recall": recall_score(
        y_test,
        tuned_xgb_test_pred,
        zero_division=0,
    ),
    "f1": f1_score(
        y_test,
        tuned_xgb_test_pred,
        zero_division=0,
    ),
    "roc_auc": roc_auc_score(
        y_test,
        tuned_xgb_test_proba,
    ),
}

print("Tuned XGBoost — Final Test Results")
print("Threshold:", 0.52)

for metric, value in tuned_xgb_test_metrics.items():
    print(f"{metric.upper():10}: {value:.4f}")

Tuned XGBoost — Final Test Results
Threshold: 0.52
ACCURACY  : 0.6975
PRECISION : 0.1837
RECALL    : 0.5167
F1        : 0.2711
ROC_AUC   : 0.6688

In [65]:
# Compare original and tuned XGBoost using five patient-level cross-validation folds
from sklearn.model_selection import GroupKFold

# Recover patient IDs only for grouping; patient IDs are NOT used as model features
train_groups = X_train.loc[
    X_train_model.index,
    "patient_nbr"
]

group_kfold = GroupKFold(n_splits=5)

cv_results = []

for fold, (train_idx, validation_idx) in enumerate(
    group_kfold.split(
        X_train_processed,
        y_train,
        groups=train_groups,
    ),
    start=1,
):
    print(f"Training fold {fold}/5...")

    # Split the already-preprocessed training data
    X_fold_train = X_train_processed[train_idx]
    X_fold_validation = X_train_processed[validation_idx]

    y_fold_train = y_train.iloc[train_idx]
    y_fold_validation = y_train.iloc[validation_idx]

    # Calculate class weight using only the current training fold
    fold_negative_count = (y_fold_train == 0).sum()
    fold_positive_count = (y_fold_train == 1).sum()

    fold_scale_pos_weight = (
        fold_negative_count / fold_positive_count
    )

    # Original XGBoost configuration
    original_model_cv = XGBClassifier(
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=42,
        n_jobs=-1,
        scale_pos_weight=fold_scale_pos_weight,
        n_estimators=300,
        max_depth=4,
        learning_rate=0.05,
        min_child_weight=5,
        subsample=0.8,
        colsample_bytree=0.8,
    )

    original_model_cv.fit(
        X_fold_train,
        y_fold_train,
    )

    original_proba_cv = original_model_cv.predict_proba(
        X_fold_validation
    )[:, 1]

    original_auc_cv = roc_auc_score(
        y_fold_validation,
        original_proba_cv,
    )

    # Tuned XGBoost configuration
    tuned_model_cv = XGBClassifier(
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=42,
        n_jobs=-1,
        scale_pos_weight=fold_scale_pos_weight,
        n_estimators=400,
        max_depth=5,
        learning_rate=0.03,
        min_child_weight=5,
        subsample=0.8,
        colsample_bytree=0.8,
    )

    tuned_model_cv.fit(
        X_fold_train,
        y_fold_train,
    )

    tuned_proba_cv = tuned_model_cv.predict_proba(
        X_fold_validation
    )[:, 1]

    tuned_auc_cv = roc_auc_score(
        y_fold_validation,
        tuned_proba_cv,
    )

    cv_results.append({
        "fold": fold,
        "original_xgb_roc_auc": original_auc_cv,
        "tuned_xgb_roc_auc": tuned_auc_cv,
    })

    print(
        f"Original: {original_auc_cv:.4f} | "
        f"Tuned: {tuned_auc_cv:.4f}"
    )

cv_results_df = pd.DataFrame(cv_results)

print("\nCross-validation results:")
display(cv_results_df.round(4))

print("\nMean ROC-AUC:")
print(
    "Original XGBoost:",
    round(
        cv_results_df["original_xgb_roc_auc"].mean(),
        4,
    ),
)

print(
    "Tuned XGBoost:",
    round(
        cv_results_df["tuned_xgb_roc_auc"].mean(),
        4,
    ),
)

Training fold 1/5...
Original: 0.6675 | Tuned: 0.6696
Training fold 2/5...
Original: 0.6859 | Tuned: 0.6867
Training fold 3/5...
Original: 0.6633 | Tuned: 0.6635
Training fold 4/5...
Original: 0.6663 | Tuned: 0.6683
Training fold 5/5...
Original: 0.6635 | Tuned: 0.6628

Cross-validation results:

   fold  original_xgb_roc_auc  tuned_xgb_roc_auc
0     1                0.6675             0.6696
1     2                0.6859             0.6867
2     3                0.6633             0.6635
3     4                0.6663             0.6683
4     5                0.6635             0.6628

Mean ROC-AUC:
Original XGBoost: 0.6693
Tuned XGBoost: 0.6702

In [66]:
# Evaluate the tuned XGBoost using ROC-AUC and Precision-Recall metrics for the imbalanced target
from sklearn.metrics import average_precision_score

tuned_xgb_test_ap = average_precision_score(
    y_test,
    tuned_xgb_test_proba,
)

print("Tuned XGBoost — Imbalanced Classification Metrics")
print(f"ROC-AUC : {tuned_xgb_test_metrics['roc_auc']:.4f}")
print(f"PR-AUC  : {tuned_xgb_test_ap:.4f}")
print(f"Precision: {tuned_xgb_test_metrics['precision']:.4f}")
print(f"Recall   : {tuned_xgb_test_metrics['recall']:.4f}")
print(f"F1       : {tuned_xgb_test_metrics['f1']:.4f}")

Tuned XGBoost — Imbalanced Classification Metrics
ROC-AUC : 0.6688
PR-AUC  : 0.2188
Precision: 0.1837
Recall   : 0.5167
F1       : 0.2711

In [67]:
# Extract the actual 2,189 feature names created by preprocessing and match them with XGBoost importance
feature_names = preprocessor.get_feature_names_out()

feature_importance = pd.DataFrame({
    "feature": feature_names,
    "importance": best_xgb_model.feature_importances_,
})

feature_importance = (
    feature_importance
    .sort_values("importance", ascending=False)
    .reset_index(drop=True)
)

print("Total processed features:", len(feature_names))
print("Total XGBoost importance values:", len(best_xgb_model.feature_importances_))

print("\nTop 20 features influencing readmission prediction:")

display(
    feature_importance.head(20).round(4)
)

Total processed features: 2189
Total XGBoost importance values: 2189

Top 20 features influencing readmission prediction:

                                      feature  importance
0                   numeric__number_inpatient      0.0185
1     categorical__discharge_disposition_id_1      0.0177
2    categorical__discharge_disposition_id_22      0.0103
3                     categorical__diag_1_715      0.0064
4     categorical__discharge_disposition_id_3      0.0059
5                     categorical__diag_1_V58      0.0049
6     categorical__discharge_disposition_id_5      0.0046
7    categorical__discharge_disposition_id_25      0.0044
8                     categorical__diag_1_428      0.0042
9                     categorical__diag_1_402      0.0042
10  categorical__medical_specialty_Psychiatry      0.0041
11                     categorical__diag_2_38      0.0041
12   categorical__discharge_disposition_id_28      0.0040
13                    categorical__diag_1_V57      0.0039
14   categorical__discharge_disposition_id_23      0.0039
15                    categorical__diag_2_585      0.0038
16                categorical__diag_3_Missing      0.0037
17                    categorical__diag_1_296      0.0037
18                    categorical__diag_1_786      0.0036
19                  numeric__number_emergency      0.0035

In [68]:
# Check features that may contain information only known near or after discharge
potential_leakage_columns = [
    "discharge_disposition_id",
    "time_in_hospital",
    "number_inpatient",
    "number_emergency",
    "number_outpatient",
]

print("Potentially time-dependent features:")
for column in potential_leakage_columns:
    if column in X.columns:
        print(f"- {column}")

Potentially time-dependent features:
- discharge_disposition_id
- time_in_hospital
- number_inpatient
- number_emergency
- number_outpatient

In [69]:
# Compare 30-day readmission rates across discharge disposition categories
discharge_readmission_rate = (
    pd.crosstab(
        X["discharge_disposition_id"],
        y_binary,
        normalize="index",
    )
    .rename(columns={
        0: "not_readmitted_rate",
        1: "readmitted_within_30_days_rate",
    })
    .sort_values(
        "readmitted_within_30_days_rate",
        ascending=False,
    )
)

display(
    discharge_readmission_rate.round(4)
)

readmitted                not_readmitted_rate  readmitted_within_30_days_rate
discharge_disposition_id
12                                     0.3333                          0.6667
15                                     0.5556                          0.4444
9                                      0.5714                          0.4286
28                                     0.6331                          0.3669
22                                     0.7230                          0.2770
5                                      0.7914                          0.2086
2                                      0.8393                          0.1607
3                                      0.8534                          0.1466
24                                     0.8542                          0.1458
7                                      0.8555                          0.1445
8                                      0.8611                          0.1389
4                                      0.8724                          0.1276
6                                      0.8730                          0.1270
18                                     0.8756                          0.1244
25                                     0.9070                          0.0930
1                                      0.9070                          0.0930
23                                     0.9272                          0.0728
14                                     0.9355                          0.0645
13                                     0.9524                          0.0476
10                                     1.0000                          0.0000
11                                     1.0000                          0.0000
16                                     1.0000                          0.0000
17                                     1.0000                          0.0000
20                                     1.0000                          0.0000
19                                     1.0000                          0.0000
27                                     1.0000                          0.0000

In [70]:
# Remove discharge disposition because it is only known near discharge and can cause temporal leakage
leakage_column = "discharge_disposition_id"

X_train_no_leak = X_train_model.drop(
    columns=[leakage_column]
)

X_validation_no_leak = X_validation_model.drop(
    columns=[leakage_column]
)

X_test_no_leak = X_test_model.drop(
    columns=[leakage_column]
)

print("Removed leakage-prone feature:", leakage_column)
print(
    "Training features remaining:",
    X_train_no_leak.shape[1],
)
print(
    "Validation features remaining:",
    X_validation_no_leak.shape[1],
)
print(
    "Test features remaining:",
    X_test_no_leak.shape[1],
)

Removed leakage-prone feature: discharge_disposition_id
Training features remaining: 42
Validation features remaining: 42
Test features remaining: 42

In [71]:
# Build a new preprocessing pipeline after removing the leakage-prone discharge disposition feature
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Identify numerical and categorical features from the leakage-controlled training data
no_leak_numeric_columns = X_train_no_leak.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

no_leak_categorical_columns = X_train_no_leak.select_dtypes(
    include=["object"]
).columns.tolist()

# Numerical preprocessing: median imputation followed by standardization
no_leak_numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
])

# Categorical preprocessing: fill missing values and apply one-hot encoding
no_leak_categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="constant", fill_value="Missing")),
    (
        "onehot",
        OneHotEncoder(
            handle_unknown="ignore",
            min_frequency=0.01,
        ),
    ),
])

# Combine numerical and categorical preprocessing
no_leak_preprocessor = ColumnTransformer([
    (
        "numeric",
        no_leak_numeric_pipeline,
        no_leak_numeric_columns,
    ),
    (
        "categorical",
        no_leak_categorical_pipeline,
        no_leak_categorical_columns,
    ),
])

print("Leakage-controlled preprocessing pipeline created.")
print("Numerical features:", len(no_leak_numeric_columns))
print("Categorical features:", len(no_leak_categorical_columns))
print(
    "Total input features:",
    len(no_leak_numeric_columns) + len(no_leak_categorical_columns),
)

Leakage-controlled preprocessing pipeline created.
Numerical features: 8
Categorical features: 34
Total input features: 42

In [72]:
# Fit the leakage-controlled preprocessor on training data and transform validation and test data
X_train_no_leak_processed = no_leak_preprocessor.fit_transform(
    X_train_no_leak
)

X_validation_no_leak_processed = no_leak_preprocessor.transform(
    X_validation_no_leak
)

X_test_no_leak_processed = no_leak_preprocessor.transform(
    X_test_no_leak
)

print(
    "Training processed shape:",
    X_train_no_leak_processed.shape,
)

print(
    "Validation processed shape:",
    X_validation_no_leak_processed.shape,
)

print(
    "Test processed shape:",
    X_test_no_leak_processed.shape,
)

Training processed shape: (79527, 178)
Validation processed shape: (9894, 178)
Test processed shape: (9922, 178)

In [73]:
# Train XGBoost without the leakage-prone discharge disposition feature
leakage_controlled_xgb = XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,
    n_jobs=-1,
    scale_pos_weight=scale_pos_weight,
    n_estimators=400,
    max_depth=5,
    learning_rate=0.03,
    min_child_weight=5,
    subsample=0.8,
    colsample_bytree=0.8,
)

leakage_controlled_xgb.fit(
    X_train_no_leak_processed,
    y_train,
)

print("Leakage-controlled XGBoost trained successfully.")

Leakage-controlled XGBoost trained successfully.

In [74]:
# Evaluate the leakage-controlled XGBoost on the validation set using all required metrics
leakage_controlled_val_proba = leakage_controlled_xgb.predict_proba(
    X_validation_no_leak_processed
)[:, 1]

leakage_controlled_val_pred = (
    leakage_controlled_val_proba >= 0.50
).astype(int)

leakage_controlled_val_metrics = {
    "accuracy": accuracy_score(
        y_validation,
        leakage_controlled_val_pred,
    ),
    "precision": precision_score(
        y_validation,
        leakage_controlled_val_pred,
        zero_division=0,
    ),
    "recall": recall_score(
        y_validation,
        leakage_controlled_val_pred,
        zero_division=0,
    ),
    "f1": f1_score(
        y_validation,
        leakage_controlled_val_pred,
        zero_division=0,
    ),
    "roc_auc": roc_auc_score(
        y_validation,
        leakage_controlled_val_proba,
    ),
}

print("Leakage-Controlled XGBoost — Validation Results")

for metric, value in leakage_controlled_val_metrics.items():
    print(f"{metric.upper():10}: {value:.4f}")

Leakage-Controlled XGBoost — Validation Results
ACCURACY  : 0.6699
PRECISION : 0.1766
RECALL    : 0.5533
F1        : 0.2677
ROC_AUC   : 0.6636

In [75]:
# Find the probability threshold that gives the leakage-controlled XGBoost the best validation F1
leakage_thresholds = np.arange(0.30, 0.71, 0.01)

leakage_threshold_results = []

for threshold in leakage_thresholds:
    predictions = (
        leakage_controlled_val_proba >= threshold
    ).astype(int)

    leakage_threshold_results.append({
        "threshold": threshold,
        "precision": precision_score(
            y_validation,
            predictions,
            zero_division=0,
        ),
        "recall": recall_score(
            y_validation,
            predictions,
            zero_division=0,
        ),
        "f1": f1_score(
            y_validation,
            predictions,
            zero_division=0,
        ),
    })

leakage_threshold_results = pd.DataFrame(
    leakage_threshold_results
)

best_leakage_threshold = leakage_threshold_results.loc[
    leakage_threshold_results["f1"].idxmax()
]

print("Best threshold for leakage-controlled XGBoost:")
print(best_leakage_threshold)

display(
    leakage_threshold_results.round(4)
)

Best threshold for leakage-controlled XGBoost:
threshold    0.540000
precision    0.200764
recall       0.438369
f1           0.275400
Name: 24, dtype: float64

    threshold  precision  recall      f1
0        0.30     0.1185  0.9601  0.2109
1        0.31     0.1195  0.9500  0.2123
2        0.32     0.1208  0.9379  0.2141
3        0.33     0.1218  0.9268  0.2154
4        0.34     0.1237  0.9157  0.2180
5        0.35     0.1255  0.9027  0.2204
6        0.36     0.1277  0.8879  0.2233
7        0.37     0.1293  0.8693  0.2251
8        0.38     0.1317  0.8563  0.2283
9        0.39     0.1345  0.8415  0.2319
10       0.40     0.1365  0.8165  0.2339
11       0.41     0.1398  0.7980  0.2379
12       0.42     0.1439  0.7766  0.2428
13       0.43     0.1476  0.7516  0.2467
14       0.44     0.1511  0.7275  0.2502
15       0.45     0.1524  0.6914  0.2498
16       0.46     0.1570  0.6664  0.2541
17       0.47     0.1590  0.6256  0.2536
18       0.48     0.1657  0.6043  0.2601
19       0.49     0.1712  0.5829  0.2647
20       0.50     0.1766  0.5533  0.2677
21       0.51     0.1812  0.5236  0.2692
22       0.52     0.1892  0.5014  0.2748
23       0.53     0.1947  0.4699  0.2753
24       0.54     0.2008  0.4384  0.2754
25       0.55     0.2027  0.4004  0.2692
26       0.56     0.2105  0.3800  0.2709
27       0.57     0.2163  0.3540  0.2685
28       0.58     0.2171  0.3197  0.2586
29       0.59     0.2281  0.3012  0.2596
30       0.60     0.2358  0.2780  0.2552
31       0.61     0.2367  0.2512  0.2437
32       0.62     0.2373  0.2289  0.2330
33       0.63     0.2448  0.2067  0.2241
34       0.64     0.2531  0.1891  0.2164
35       0.65     0.2545  0.1696  0.2036
36       0.66     0.2580  0.1501  0.1898
37       0.67     0.2679  0.1353  0.1798
38       0.68     0.2945  0.1242  0.1747
39       0.69     0.3120  0.1131  0.1660
40       0.70     0.3323  0.1010  0.1549

In [76]:
# Evaluate the leakage-controlled XGBoost on the test set using the validation-selected threshold of 0.54
leakage_controlled_test_proba = leakage_controlled_xgb.predict_proba(
    X_test_no_leak_processed
)[:, 1]

leakage_controlled_test_pred = (
    leakage_controlled_test_proba >= 0.54
).astype(int)

leakage_controlled_test_metrics = {
    "accuracy": accuracy_score(
        y_test,
        leakage_controlled_test_pred,
    ),
    "precision": precision_score(
        y_test,
        leakage_controlled_test_pred,
        zero_division=0,
    ),
    "recall": recall_score(
        y_test,
        leakage_controlled_test_pred,
        zero_division=0,
    ),
    "f1": f1_score(
        y_test,
        leakage_controlled_test_pred,
        zero_division=0,
    ),
    "roc_auc": roc_auc_score(
        y_test,
        leakage_controlled_test_proba,
    ),
}

print("Leakage-Controlled XGBoost — Final Test Results")
print("Threshold:", 0.54)

for metric, value in leakage_controlled_test_metrics.items():
    print(f"{metric.upper():10}: {value:.4f}")

Leakage-Controlled XGBoost — Final Test Results
Threshold: 0.54
ACCURACY  : 0.7382
PRECISION : 0.1897
RECALL    : 0.4296
F1        : 0.2632
ROC_AUC   : 0.6511

In [77]:
# Check whether time_in_hospital should be excluded for an admission-time prediction model
print("time_in_hospital summary:")
print(
    X["time_in_hospital"].describe()
)

print("\nReadmission rate by length of stay:")

stay_readmission_rate = (
    pd.crosstab(
        X["time_in_hospital"],
        y_binary,
        normalize="index",
    )
    .rename(columns={
        0: "not_readmitted_rate",
        1: "readmitted_within_30_days_rate",
    })
)

display(
    stay_readmission_rate.round(4)
)

time_in_hospital summary:
count    101766.000000
mean          4.395987
std           2.985108
min           1.000000
25%           2.000000
50%           4.000000
75%           6.000000
max          14.000000
Name: time_in_hospital, dtype: float64

Readmission rate by length of stay:

readmitted        not_readmitted_rate  readmitted_within_30_days_rate
time_in_hospital
1                              0.9182                          0.0818
2                              0.9006                          0.0994
3                              0.8933                          0.1067
4                              0.8819                          0.1181
5                              0.8797                          0.1203
6                              0.8741                          0.1259
7                              0.8717                          0.1283
8                              0.8577                          0.1423
9                              0.8628                          0.1372
10                             0.8565                          0.1435
11                             0.8949                          0.1051
12                             0.8667                          0.1333
13                             0.8769                          0.1231
14                             0.8704                          0.1296

In [78]:
# Remove features that may not be available at an early prediction stage
time_dependent_columns = [
    "discharge_disposition_id",
    "time_in_hospital",
]

X_train_early = X_train_model.drop(
    columns=time_dependent_columns
)

X_validation_early = X_validation_model.drop(
    columns=time_dependent_columns
)

X_test_early = X_test_model.drop(
    columns=time_dependent_columns
)

print("Removed time-dependent features:", time_dependent_columns)
print("Training features remaining:", X_train_early.shape[1])
print("Validation features remaining:", X_validation_early.shape[1])
print("Test features remaining:", X_test_early.shape[1])

Removed time-dependent features: ['discharge_disposition_id', 'time_in_hospital']
Training features remaining: 41
Validation features remaining: 41
Test features remaining: 41

In [79]:
# Identify numerical and categorical features for the early-prediction model

early_numerical_columns = X_train_early.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

early_categorical_columns = X_train_early.select_dtypes(
    include=["object", "category"]
).columns.tolist()

print("Number of numerical features:", len(early_numerical_columns))
print("Number of categorical features:", len(early_categorical_columns))
print("Total input features:", len(
    early_numerical_columns + early_categorical_columns
))

Number of numerical features: 7
Number of categorical features: 34
Total input features: 41

In [80]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

early_numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
])

early_categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(
        strategy="constant",
        fill_value="Missing"
    )),
    ("encoder", OneHotEncoder(
        handle_unknown="ignore",
        min_frequency=0.01
    )),
])

early_preprocessor = ColumnTransformer([
    (
        "numeric",
        early_numeric_pipeline,
        early_numerical_columns
    ),
    (
        "categorical",
        early_categorical_pipeline,
        early_categorical_columns
    ),
])

print("Early-prediction preprocessing pipeline created successfully.")

Early-prediction preprocessing pipeline created successfully.

In [81]:
for data in [
    X_train_early,
    X_validation_early,
    X_test_early
]:
    data[early_categorical_columns] = (
        data[early_categorical_columns]
        .astype(object)
        .where(
            data[early_categorical_columns].notna(),
            np.nan
        )
    )

print("Categorical missing values converted successfully.")

Categorical missing values converted successfully.

In [82]:
X_train_early_processed = early_preprocessor.fit_transform(
    X_train_early
)

X_validation_early_processed = early_preprocessor.transform(
    X_validation_early
)

X_test_early_processed = early_preprocessor.transform(
    X_test_early
)

print(
    "Training processed shape:",
    X_train_early_processed.shape
)

print(
    "Validation processed shape:",
    X_validation_early_processed.shape
)

print(
    "Test processed shape:",
    X_test_early_processed.shape
)

Training processed shape: (79527, 177)
Validation processed shape: (9894, 177)
Test processed shape: (9922, 177)

In [83]:
# Train XGBoost for strict early readmission prediction
early_xgb = XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,
    n_jobs=-1,
    scale_pos_weight=scale_pos_weight,
    n_estimators=400,
    max_depth=5,
    learning_rate=0.03,
    min_child_weight=5,
    subsample=0.8,
    colsample_bytree=0.8,
)

early_xgb.fit(
    X_train_early_processed,
    y_train,
)

print("Early-prediction XGBoost trained successfully.")

Early-prediction XGBoost trained successfully.

In [84]:
# Evaluate the strict early-prediction XGBoost on the validation set

early_val_proba = early_xgb.predict_proba(
    X_validation_early_processed
)[:, 1]

early_val_pred = (
    early_val_proba >= 0.50
).astype(int)

early_val_metrics = {
    "accuracy": accuracy_score(
        y_validation,
        early_val_pred,
    ),
    "precision": precision_score(
        y_validation,
        early_val_pred,
        zero_division=0,
    ),
    "recall": recall_score(
        y_validation,
        early_val_pred,
        zero_division=0,
    ),
    "f1": f1_score(
        y_validation,
        early_val_pred,
        zero_division=0,
    ),
    "roc_auc": roc_auc_score(
        y_validation,
        early_val_proba,
    ),
}

print("Early-Prediction XGBoost — Validation Results")

for metric, value in early_val_metrics.items():
    print(f"{metric.upper():10}: {value:.4f}")

Early-Prediction XGBoost — Validation Results
ACCURACY  : 0.6770
PRECISION : 0.1760
RECALL    : 0.5329
F1        : 0.2646
ROC_AUC   : 0.6568

In [85]:
# Find the best classification threshold for the early-prediction model

early_thresholds = np.arange(0.30, 0.71, 0.01)

early_threshold_results = []

for threshold in early_thresholds:
    predictions = (
        early_val_proba >= threshold
    ).astype(int)

    early_threshold_results.append({
        "threshold": threshold,
        "precision": precision_score(
            y_validation,
            predictions,
            zero_division=0,
        ),
        "recall": recall_score(
            y_validation,
            predictions,
            zero_division=0,
        ),
        "f1": f1_score(
            y_validation,
            predictions,
            zero_division=0,
        ),
    })

early_threshold_results = pd.DataFrame(
    early_threshold_results
)

best_early_threshold = early_threshold_results.loc[
    early_threshold_results["f1"].idxmax()
]

print("Best threshold for Early-Prediction XGBoost:")
print(best_early_threshold)

display(
    early_threshold_results.round(4)
)

Best threshold for Early-Prediction XGBoost:
threshold    0.550000
precision    0.202614
recall       0.402224
f1           0.269482
Name: 25, dtype: float64

    threshold  precision  recall      f1
0        0.30     0.1169  0.9574  0.2084
1        0.31     0.1179  0.9500  0.2098
2        0.32     0.1196  0.9444  0.2124
3        0.33     0.1207  0.9333  0.2138
4        0.34     0.1222  0.9203  0.2157
5        0.35     0.1241  0.9073  0.2184
6        0.36     0.1259  0.8906  0.2206
7        0.37     0.1277  0.8777  0.2230
8        0.38     0.1293  0.8591  0.2248
9        0.39     0.1317  0.8406  0.2277
10       0.40     0.1343  0.8174  0.2306
11       0.41     0.1370  0.7943  0.2337
12       0.42     0.1405  0.7729  0.2377
13       0.43     0.1426  0.7405  0.2391
14       0.44     0.1473  0.7155  0.2443
15       0.45     0.1506  0.6849  0.2469
16       0.46     0.1552  0.6534  0.2508
17       0.47     0.1601  0.6219  0.2546
18       0.48     0.1644  0.5941  0.2576
19       0.49     0.1698  0.5616  0.2608
20       0.50     0.1760  0.5329  0.2646
21       0.51     0.1812  0.5051  0.2668
22       0.52     0.1845  0.4736  0.2655
23       0.53     0.1903  0.4467  0.2669
24       0.54     0.1947  0.4189  0.2659
25       0.55     0.2026  0.4022  0.2695
26       0.56     0.2080  0.3726  0.2669
27       0.57     0.2156  0.3485  0.2664
28       0.58     0.2199  0.3179  0.2599
29       0.59     0.2228  0.2947  0.2538
30       0.60     0.2240  0.2669  0.2436
31       0.61     0.2352  0.2512  0.2429
32       0.62     0.2399  0.2308  0.2352
33       0.63     0.2424  0.2057  0.2226
34       0.64     0.2497  0.1844  0.2122
35       0.65     0.2593  0.1677  0.2037
36       0.66     0.2689  0.1520  0.1942
37       0.67     0.2775  0.1335  0.1802
38       0.68     0.3000  0.1251  0.1766
39       0.69     0.3026  0.1066  0.1576
40       0.70     0.3125  0.0927  0.1430

In [86]:
# Final evaluation of the strict early-prediction XGBoost
# using the threshold selected from the validation set

early_test_proba = early_xgb.predict_proba(
    X_test_early_processed
)[:, 1]

early_test_pred = (
    early_test_proba >= 0.55
).astype(int)

early_test_metrics = {
    "accuracy": accuracy_score(
        y_test,
        early_test_pred,
    ),
    "precision": precision_score(
        y_test,
        early_test_pred,
        zero_division=0,
    ),
    "recall": recall_score(
        y_test,
        early_test_pred,
        zero_division=0,
    ),
    "f1": f1_score(
        y_test,
        early_test_pred,
        zero_division=0,
    ),
    "roc_auc": roc_auc_score(
        y_test,
        early_test_proba,
    ),
}

print("Early-Prediction XGBoost — Final Test Results")
print("Threshold: 0.55")

for metric, value in early_test_metrics.items():
    print(f"{metric.upper():10}: {value:.4f}")

Early-Prediction XGBoost — Final Test Results
Threshold: 0.55
ACCURACY  : 0.7605
PRECISION : 0.2000
RECALL    : 0.4000
F1        : 0.2667
ROC_AUC   : 0.6498

In [87]:
# Compare different class-imbalance weights for XGBoost
from sklearn.metrics import average_precision_score

class_weight_values = [
    3.0,
    5.0,
    7.69,
    9.0,
    11.0,
]

imbalance_results = []

for weight in class_weight_values:
    print(f"Training XGBoost with scale_pos_weight = {weight}")

    model = XGBClassifier(
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=42,
        n_jobs=-1,
        scale_pos_weight=weight,
        n_estimators=400,
        max_depth=5,
        learning_rate=0.03,
        min_child_weight=5,
        subsample=0.8,
        colsample_bytree=0.8,
    )

    model.fit(
        X_train_early_processed,
        y_train,
    )

    val_proba = model.predict_proba(
        X_validation_early_processed
    )[:, 1]

    val_pred = (
        val_proba >= 0.50
    ).astype(int)

    imbalance_results.append({
        "scale_pos_weight": weight,
        "accuracy": accuracy_score(
            y_validation,
            val_pred,
        ),
        "precision": precision_score(
            y_validation,
            val_pred,
            zero_division=0,
        ),
        "recall": recall_score(
            y_validation,
            val_pred,
            zero_division=0,
        ),
        "f1": f1_score(
            y_validation,
            val_pred,
            zero_division=0,
        ),
        "roc_auc": roc_auc_score(
            y_validation,
            val_proba,
        ),
        "pr_auc": average_precision_score(
            y_validation,
            val_proba,
        ),
    })

imbalance_results = pd.DataFrame(
    imbalance_results
)

display(
    imbalance_results.round(4)
)

Training XGBoost with scale_pos_weight = 3.0
Training XGBoost with scale_pos_weight = 5.0
Training XGBoost with scale_pos_weight = 7.69
Training XGBoost with scale_pos_weight = 9.0
Training XGBoost with scale_pos_weight = 11.0

   scale_pos_weight  accuracy  precision  recall      f1  roc_auc  pr_auc
0              3.00    0.8818     0.3346  0.0843  0.1347   0.6615  0.2121
1              5.00    0.8235     0.2351  0.2743  0.2532   0.6581  0.2099
2              7.69    0.6750     0.1759  0.5375  0.2651   0.6579  0.2080
3              9.00    0.5783     0.1561  0.6506  0.2518   0.6574  0.2069
4             11.00    0.4452     0.1384  0.7822  0.2352   0.6549  0.2071

In [88]:
# Find the best validation threshold for each class weight

weight_threshold_results = []

for weight in class_weight_values:

    model = XGBClassifier(
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=42,
        n_jobs=-1,
        scale_pos_weight=weight,
        n_estimators=400,
        max_depth=5,
        learning_rate=0.03,
        min_child_weight=5,
        subsample=0.8,
        colsample_bytree=0.8,
    )

    model.fit(
        X_train_early_processed,
        y_train,
    )

    val_proba = model.predict_proba(
        X_validation_early_processed
    )[:, 1]

    best_f1 = -1
    best_threshold = None
    best_precision = None
    best_recall = None

    for threshold in np.arange(0.30, 0.71, 0.01):

        val_pred = (
            val_proba >= threshold
        ).astype(int)

        precision = precision_score(
            y_validation,
            val_pred,
            zero_division=0,
        )

        recall = recall_score(
            y_validation,
            val_pred,
            zero_division=0,
        )

        f1 = f1_score(
            y_validation,
            val_pred,
            zero_division=0,
        )

        if f1 > best_f1:
            best_f1 = f1
            best_threshold = threshold
            best_precision = precision
            best_recall = recall

    weight_threshold_results.append({
        "scale_pos_weight": weight,
        "best_threshold": best_threshold,
        "precision": best_precision,
        "recall": best_recall,
        "f1": best_f1,
        "roc_auc": roc_auc_score(
            y_validation,
            val_proba,
        ),
        "pr_auc": average_precision_score(
            y_validation,
            val_proba,
        ),
    })

weight_threshold_results = pd.DataFrame(
    weight_threshold_results
)

display(
    weight_threshold_results.round(4)
)

,scale_pos_weight,best_threshold,precision,recall,f1,roc_auc,pr_auc
0,3.00,0.33,0.2069,0.3948,0.2715,0.6615,0.2121
1,5.00,0.41,0.1859,0.5005,0.2711,0.6581,0.2099
2,7.69,0.56,0.2101,0.3791,0.2703,0.6579,0.2080
3,9.00,0.56,0.1892,0.4727,0.2702,0.6574,0.2069
4,11.00,0.62,0.1958,0.4356,0.2701,0.6549,0.2071

In [89]:
# Final test comparison of the two strongest class-weight configurations

final_configs = [
    {
        "name": "Weight 3.0",
        "scale_pos_weight": 3.0,
        "threshold": 0.33,
    },
    {
        "name": "Weight 5.0",
        "scale_pos_weight": 5.0,
        "threshold": 0.41,
    },
]

final_test_results = []

for config in final_configs:

    model = XGBClassifier(
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=42,
        n_jobs=-1,
        scale_pos_weight=config["scale_pos_weight"],
        n_estimators=400,
        max_depth=5,
        learning_rate=0.03,
        min_child_weight=5,
        subsample=0.8,
        colsample_bytree=0.8,
    )

    model.fit(
        X_train_early_processed,
        y_train,
    )

    test_proba = model.predict_proba(
        X_test_early_processed
    )[:, 1]

    test_pred = (
        test_proba >= config["threshold"]
    ).astype(int)

    final_test_results.append({
        "model": config["name"],
        "threshold": config["threshold"],
        "accuracy": accuracy_score(
            y_test,
            test_pred,
        ),
        "precision": precision_score(
            y_test,
            test_pred,
            zero_division=0,
        ),
        "recall": recall_score(
            y_test,
            test_pred,
            zero_division=0,
        ),
        "f1": f1_score(
            y_test,
            test_pred,
            zero_division=0,
        ),
        "roc_auc": roc_auc_score(
            y_test,
            test_proba,
        ),
        "pr_auc": average_precision_score(
            y_test,
            test_proba,
        ),
    })

final_test_results = pd.DataFrame(
    final_test_results
)

print("Final Test Comparison")
display(
    final_test_results.round(4)
)

Final Test Comparison

        model  threshold  accuracy  precision  recall      f1  roc_auc  pr_auc
0  Weight 3.0       0.33    0.7602     0.1980  0.3944  0.2637   0.6517  0.2017
1  Weight 5.0       0.41    0.6953     0.1752  0.4852  0.2574   0.6520  0.1990

In [90]:
# Build the selected early-prediction XGBoost model
# Selected based on validation tuning and final test comparison

selected_early_xgb = XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,
    n_jobs=-1,
    scale_pos_weight=3.0,
    n_estimators=400,
    max_depth=5,
    learning_rate=0.03,
    min_child_weight=5,
    subsample=0.8,
    colsample_bytree=0.8,
)

selected_early_xgb.fit(
    X_train_early_processed,
    y_train,
)

selected_threshold = 0.33

print("Selected early-prediction XGBoost trained successfully.")
print("scale_pos_weight:", 3.0)
print("Decision threshold:", selected_threshold)

Selected early-prediction XGBoost trained successfully.
scale_pos_weight: 3.0
Decision threshold: 0.33

In [92]:
# Get feature names generated by the early-prediction preprocessor

early_feature_names = (
    early_preprocessor
    .get_feature_names_out()
)

print("Total processed features:", len(early_feature_names))
print("Total XGBoost importance values:",
      len(selected_early_xgb.feature_importances_))

feature_importance = pd.DataFrame({
    "feature": early_feature_names,
    "importance": selected_early_xgb.feature_importances_,
})

feature_importance = feature_importance.sort_values(
    by="importance",
    ascending=False,
).reset_index(drop=True)

print("\nTop 20 features influencing early readmission prediction:")

display(
    feature_importance.head(20).round(4)
)

Total processed features: 177
Total XGBoost importance values: 177

Top 20 features influencing early readmission prediction:

                                              feature  importance
0                           numeric__number_inpatient      0.0536
1                             categorical__diag_1_434      0.0150
2                             categorical__diag_1_786      0.0122
3                             categorical__diag_1_820      0.0104
4   categorical__admission_source_id_infrequent_sk...      0.0093
5                           numeric__number_diagnoses      0.0092
6           categorical__medical_specialty_Cardiology      0.0091
7                           numeric__number_emergency      0.0090
8                         categorical__diabetesMed_No      0.0090
9                             categorical__diag_2_707      0.0089
10                           categorical__age_[50-60)      0.0089
11                            categorical__diag_3_401      0.0087
12                           categorical__age_[80-90)      0.0085
13                            categorical__diag_2_401      0.0082
14                            categorical__diag_1_250      0.0082
15                          categorical__age_[90-100)      0.0082
16                        categorical__diag_3_Missing      0.0081
17                          categorical__insulin_Down      0.0077
18                            categorical__diag_3_585      0.0075
19                           categorical__age_[70-80)      0.0075

In [93]:
# Group one-hot encoded features back into their original clinical features

def get_original_feature(feature_name):
    if feature_name.startswith("numeric__"):
        return feature_name.replace("numeric__", "")

    if feature_name.startswith("categorical__"):
        feature_name = feature_name.replace("categorical__", "")

        # Original feature name is before the first "_"
        original_features = [
            "admission_type_id",
            "admission_source_id",
            "age",
            "diag_1",
            "diag_2",
            "diag_3",
            "medical_specialty",
            "race",
            "gender",
            "diabetesMed",
            "changeMed",
            "insulin",
            "A1Cresult",
            "max_glu_serum",
        ]

        for original in original_features:
            if feature_name.startswith(original + "_") or feature_name == original:
                return original

    return feature_name


feature_importance["original_feature"] = (
    feature_importance["feature"]
    .apply(get_original_feature)
)

grouped_importance = (
    feature_importance
    .groupby("original_feature")["importance"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

print("Top original clinical features:")

display(
    grouped_importance.head(20).round(4)
)

Top original clinical features:

                  original_feature  importance
0                           diag_1      0.1507
1                           diag_2      0.1367
2                           diag_3      0.1176
3                medical_specialty      0.0672
4                              age      0.0644
5                 number_inpatient      0.0536
6              admission_source_id      0.0413
7                admission_type_id      0.0339
8                             race      0.0318
9                    max_glu_serum      0.0228
10                         insulin      0.0221
11                       A1Cresult      0.0212
12                     diabetesMed      0.0160
13                number_diagnoses      0.0092
14                          gender      0.0090
15                number_emergency      0.0090
16                    metformin_No      0.0072
17                metformin_Steady      0.0069
18                  repaglinide_No      0.0069
19  glimepiride_infrequent_sklearn      0.0066

In [94]:
# Analyze the errors made by the selected early-prediction model

selected_test_proba = selected_early_xgb.predict_proba(
    X_test_early_processed
)[:, 1]

selected_test_pred = (
    selected_test_proba >= selected_threshold
).astype(int)

early_confusion = confusion_matrix(
    y_test,
    selected_test_pred,
)

tn, fp, fn, tp = early_confusion.ravel()

print("Selected Early XGBoost — Test Confusion Matrix")
print("-----------------------------------------------")
print("True Negatives :", tn)
print("False Positives:", fp)
print("False Negatives:", fn)
print("True Positives :", tp)

print("\nTotal actual readmissions:", fn + tp)
print("Readmissions correctly identified:", tp)
print("Readmissions missed:", fn)

print(
    "\nRecall:",
    round(tp / (tp + fn), 4)
)

Selected Early XGBoost — Test Confusion Matrix
-----------------------------------------------
True Negatives : 7117
False Positives: 1725
False Negatives: 654
True Positives : 426

Total actual readmissions: 1080
Readmissions correctly identified: 426
Readmissions missed: 654

Recall: 0.3944

In [95]:
# Analyze predicted probabilities for actual readmitted patients

actual_readmitted = (
    y_test == 1
)

readmitted_probabilities = selected_test_proba[
    actual_readmitted
]

print("Probability distribution for actual readmitted patients")
print("------------------------------------------------------")

print(
    pd.Series(readmitted_probabilities).describe()
)

print("\nProbability ranges:")

probability_bins = pd.cut(
    readmitted_probabilities,
    bins=[
        0.00,
        0.10,
        0.20,
        0.30,
        0.33,
        0.40,
        0.50,
        0.60,
        0.70,
        0.80,
        0.90,
        1.00,
    ],
    include_lowest=True,
)

display(
    probability_bins
    .value_counts()
    .sort_index()
)

Probability distribution for actual readmitted patients
------------------------------------------------------
count    1080.000000
mean        0.318312
std         0.122041
min         0.086473
25%         0.230239
50%         0.292573
75%         0.386593
max         0.817671
dtype: float64

Probability ranges:

(-0.001, 0.1]      3
(0.1, 0.2]       154
(0.2, 0.3]       415
(0.3, 0.33]       82
(0.33, 0.4]      190
(0.4, 0.5]       145
(0.5, 0.6]        54
(0.6, 0.7]        26
(0.7, 0.8]        10
(0.8, 0.9]         1
(0.9, 1.0]         0
Name: count, dtype: int64

In [96]:
# Analyze important thresholds on the validation set
# Test data is NOT used here.

selected_val_thresholds = [
    0.20,
    0.25,
    0.30,
    0.33,
    0.35,
    0.40,
]

selected_threshold_analysis = []

# Get validation probabilities from the selected final model
selected_val_proba = selected_early_xgb.predict_proba(
    X_validation_early_processed
)[:, 1]

for threshold in selected_val_thresholds:

    val_pred = (
        selected_val_proba >= threshold
    ).astype(int)

    selected_threshold_analysis.append({
        "threshold": threshold,
        "accuracy": accuracy_score(
            y_validation,
            val_pred,
        ),
        "precision": precision_score(
            y_validation,
            val_pred,
            zero_division=0,
        ),
        "recall": recall_score(
            y_validation,
            val_pred,
            zero_division=0,
        ),
        "f1": f1_score(
            y_validation,
            val_pred,
            zero_division=0,
        ),
    })

selected_threshold_analysis = pd.DataFrame(
    selected_threshold_analysis
)

print("Selected Early XGBoost — Validation Threshold Analysis")

display(
    selected_threshold_analysis.round(4)
)

Selected Early XGBoost — Validation Threshold Analysis

   threshold  accuracy  precision  recall      f1
0       0.20    0.3616     0.1311  0.8628  0.2277
1       0.25    0.5609     0.1544  0.6756  0.2513
2       0.30    0.7139     0.1869  0.4847  0.2698
3       0.33    0.7690     0.2069  0.3948  0.2715
4       0.35    0.7951     0.2182  0.3401  0.2658
5       0.40    0.8400     0.2455  0.2252  0.2349

In [97]:
# Final test comparison of clinically relevant thresholds
# Thresholds were selected using validation data only.

clinical_thresholds = [0.25, 0.30, 0.33]

clinical_test_results = []

for threshold in clinical_thresholds:

    test_pred = (
        selected_test_proba >= threshold
    ).astype(int)

    clinical_test_results.append({
        "threshold": threshold,
        "accuracy": accuracy_score(
            y_test,
            test_pred,
        ),
        "precision": precision_score(
            y_test,
            test_pred,
            zero_division=0,
        ),
        "recall": recall_score(
            y_test,
            test_pred,
            zero_division=0,
        ),
        "f1": f1_score(
            y_test,
            test_pred,
            zero_division=0,
        ),
        "roc_auc": roc_auc_score(
            y_test,
            selected_test_proba,
        ),
        "pr_auc": average_precision_score(
            y_test,
            selected_test_proba,
        ),
    })

clinical_test_results = pd.DataFrame(
    clinical_test_results
)

print("Clinical Threshold Comparison — Final Test")

display(
    clinical_test_results.round(4)
)

Clinical Threshold Comparison — Final Test

   threshold  accuracy  precision  recall      f1  roc_auc  pr_auc
0       0.25    0.5541     0.1515  0.6731  0.2474   0.6517  0.2017
1       0.30    0.7031     0.1763  0.4704  0.2564   0.6517  0.2017
2       0.33    0.7602     0.1980  0.3944  0.2637   0.6517  0.2017

In [98]:
# ============================================================
# FINAL MODEL CONFIGURATION
# ============================================================

FINAL_MODEL_NAME = "xgboost_early_readmission"
FINAL_MODEL_VERSION = "v1"
FINAL_THRESHOLD = 0.30
FINAL_SCALE_POS_WEIGHT = 3.0

print("Final model configuration locked:")
print("Model:", FINAL_MODEL_NAME)
print("Version:", FINAL_MODEL_VERSION)
print("Scale pos weight:", FINAL_SCALE_POS_WEIGHT)
print("Decision threshold:", FINAL_THRESHOLD)
print("Removed leakage-prone features:")
print(" - discharge_disposition_id")
print(" - time_in_hospital")

Final model configuration locked:
Model: xgboost_early_readmission
Version: v1
Scale pos weight: 3.0
Decision threshold: 0.3
Removed leakage-prone features:
 - discharge_disposition_id
 - time_in_hospital

In [99]:
# ============================================================
# TRAIN FINAL XGBOOST MODEL
# ============================================================

final_xgb = XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,
    n_jobs=-1,
    scale_pos_weight=FINAL_SCALE_POS_WEIGHT,
    n_estimators=400,
    max_depth=5,
    learning_rate=0.03,
    min_child_weight=5,
    subsample=0.8,
    colsample_bytree=0.8,
)

final_xgb.fit(
    X_train_early_processed,
    y_train,
)

print("Final XGBoost trained successfully.")
print("Model:", FINAL_MODEL_NAME)
print("Version:", FINAL_MODEL_VERSION)
print("Scale pos weight:", FINAL_SCALE_POS_WEIGHT)
print("Decision threshold:", FINAL_THRESHOLD)

Final XGBoost trained successfully.
Model: xgboost_early_readmission
Version: v1
Scale pos weight: 3.0
Decision threshold: 0.3

In [100]:
# ============================================================
# FINAL MODEL — TEST SET EVALUATION
# ============================================================

final_test_proba = final_xgb.predict_proba(
    X_test_early_processed
)[:, 1]

final_test_pred = (
    final_test_proba >= FINAL_THRESHOLD
).astype(int)

final_test_metrics = {
    "accuracy": accuracy_score(
        y_test,
        final_test_pred,
    ),
    "precision": precision_score(
        y_test,
        final_test_pred,
        zero_division=0,
    ),
    "recall": recall_score(
        y_test,
        final_test_pred,
        zero_division=0,
    ),
    "f1": f1_score(
        y_test,
        final_test_pred,
        zero_division=0,
    ),
    "roc_auc": roc_auc_score(
        y_test,
        final_test_proba,
    ),
    "pr_auc": average_precision_score(
        y_test,
        final_test_proba,
    ),
}

print("FINAL XGBOOST — TEST RESULTS")
print("=" * 40)
print("Model:", FINAL_MODEL_NAME)
print("Version:", FINAL_MODEL_VERSION)
print("Threshold:", FINAL_THRESHOLD)
print()

for metric, value in final_test_metrics.items():
    print(f"{metric.upper():10}: {value:.4f}")

FINAL XGBOOST — TEST RESULTS
========================================
Model: xgboost_early_readmission
Version: v1
Threshold: 0.3

ACCURACY  : 0.7031
PRECISION : 0.1763
RECALL    : 0.4704
F1        : 0.2564
ROC_AUC   : 0.6517
PR_AUC    : 0.2017

In [101]:
# ============================================================
# VERIFY FINAL PREPROCESSOR
# ============================================================

print("Final preprocessor:", type(early_preprocessor).__name__)

final_feature_names = (
    early_preprocessor.get_feature_names_out()
)

print("Processed feature count:", len(final_feature_names))
print("XGBoost feature count:", len(final_xgb.feature_importances_))

assert len(final_feature_names) == len(
    final_xgb.feature_importances_
), "Feature count mismatch!"

print("Feature names and model features match successfully.")

Final preprocessor: ColumnTransformer
Processed feature count: 177
XGBoost feature count: 177
Feature names and model features match successfully.

In [102]:
# ============================================================
# STEP 4 — CREATE FINAL DEPLOYABLE MODEL ARTIFACT
# ============================================================

import joblib
from pathlib import Path
from datetime import datetime

# Create artifact directory
artifact_dir = Path("artifacts")
artifact_dir.mkdir(parents=True, exist_ok=True)

# Build final artifact
final_artifact = {
    "pipeline": early_preprocessor,
    "model": final_xgb,
    "model_name": FINAL_MODEL_NAME,
    "model_version": FINAL_MODEL_VERSION,
    "decision_threshold": FINAL_THRESHOLD,
    "feature_columns": list(final_feature_names),
    "n_features": len(final_feature_names),

    # Final test metrics
    "metrics": final_test_metrics,

    # Important training configuration
    "scale_pos_weight": FINAL_SCALE_POS_WEIGHT,
    "removed_features": [
        "discharge_disposition_id",
        "time_in_hospital",
    ],

    # Training information
    "trained_at": datetime.now().isoformat(),

    # Top model drivers
    "top_drivers": (
        grouped_importance.head(20)
        .to_dict(orient="records")
    ),
}

artifact_path = artifact_dir / "readmission_model.joblib"

joblib.dump(
    final_artifact,
    artifact_path,
)

print("Final model artifact created successfully.")
print("Artifact:", artifact_path)
print("Size:", round(artifact_path.stat().st_size / (1024 * 1024), 2), "MB")
print("Features:", final_artifact["n_features"])
print("Threshold:", final_artifact["decision_threshold"])
print("Model:", final_artifact["model_name"])
print("Version:", final_artifact["model_version"])

Final model artifact created successfully.
Artifact: artifacts/readmission_model.joblib
Size: 0.98 MB
Features: 177
Threshold: 0.3
Model: xgboost_early_readmission
Version: v1

In [103]:
# ============================================================
# STEP 5 — LOAD SAVED ARTIFACT AND VERIFY IT
# ============================================================

import joblib
import numpy as np

artifact_path = Path("artifacts/readmission_model.joblib")

# Load from disk
loaded_artifact = joblib.load(artifact_path)

print("Artifact loaded successfully.")
print("Artifact type:", type(loaded_artifact).__name__)

# Verify required components
required_keys = [
    "pipeline",
    "model",
    "model_name",
    "model_version",
    "decision_threshold",
    "feature_columns",
    "metrics",
]

print("\nChecking artifact contents:")

for key in required_keys:
    print(
        f"{key:20}:",
        "✓" if key in loaded_artifact else "✗"
    )

# Verify feature count
loaded_features = loaded_artifact["feature_columns"]

print("\nFeature verification:")
print("Stored features:", len(loaded_features))
print(
    "Model features:",
    len(loaded_artifact["model"].feature_importances_)
)

assert len(loaded_features) == len(
    loaded_artifact["model"].feature_importances_
)

print("Feature count matches successfully.")

# Verify threshold
print(
    "\nStored threshold:",
    loaded_artifact["decision_threshold"]
)

assert loaded_artifact["decision_threshold"] == 0.30

print("Threshold verification passed.")

Artifact loaded successfully.
Artifact type: dict

Checking artifact contents:
pipeline            : ✓
model               : ✓
model_name          : ✓
model_version       : ✓
decision_threshold  : ✓
feature_columns     : ✓
metrics             : ✓

Feature verification:
Stored features: 177
Model features: 177
Feature count matches successfully.

Stored threshold: 0.3
Threshold verification passed.

In [105]:
# ============================================================
# STEP 6A — SHOW FINAL MODEL INPUT FEATURES
# ============================================================

expected_input_features = list(
    loaded_pipeline.feature_names_in_
)

print("Final pipeline expects:", len(expected_input_features), "input features")
print("\nExpected input columns:")

for i, feature in enumerate(expected_input_features, start=1):
    print(f"{i:2}. {feature}")

Final pipeline expects: 41 input features

Expected input columns:
 1. race
 2. gender
 3. age
 4. admission_type_id
 5. admission_source_id
 6. medical_specialty
 7. num_lab_procedures
 8. num_procedures
 9. num_medications
10. number_outpatient
11. number_emergency
12. number_inpatient
13. diag_1
14. diag_2
15. diag_3
16. number_diagnoses
17. max_glu_serum
18. A1Cresult
19. metformin
20. repaglinide
21. nateglinide
22. chlorpropamide
23. glimepiride
24. acetohexamide
25. glipizide
26. glyburide
27. tolbutamide
28. pioglitazone
29. rosiglitazone
30. acarbose
31. miglitol
32. troglitazone
33. tolazamide
34. insulin
35. glyburide-metformin
36. glipizide-metformin
37. glimepiride-pioglitazone
38. metformin-rosiglitazone
39. metformin-pioglitazone
40. change
41. diabetesMed

In [106]:
# ============================================================
# STEP 6B — DEPLOYMENT-SAFE FRESH PATIENT TEST
# ============================================================

fresh_patient = pd.DataFrame(
    {column: [np.nan] for column in expected_input_features}
)

patient_values = {
    "race": "Caucasian",
    "gender": "Female",
    "age": "[70-80)",
    "admission_type_id": 1,
    "admission_source_id": 7,
    "medical_specialty": "Cardiology",

    "diag_1": "428",
    "diag_2": "250",
    "diag_3": "401",

    "max_glu_serum": "None",
    "A1Cresult": "None",
    "insulin": "Steady",
    "diabetesMed": "Yes",
    "change": "No",

    "number_inpatient": 3,
    "number_emergency": 2,
    "number_outpatient": 1,
    "number_diagnoses": 9,
}

for column, value in patient_values.items():
    if column in fresh_patient.columns:
        fresh_patient.loc[0, column] = value

print("Fresh patient record created.")
print("Input columns:", fresh_patient.shape[1])

# Transform
fresh_processed = loaded_pipeline.transform(
    fresh_patient
)

print("Processed feature shape:", fresh_processed.shape)

# Predict
fresh_probability = loaded_model.predict_proba(
    fresh_processed
)[0, 1]

fresh_prediction = int(
    fresh_probability >= loaded_threshold
)

# Risk category
if fresh_probability >= 0.70:
    risk_category = "High"
elif fresh_probability >= 0.40:
    risk_category = "Medium"
else:
    risk_category = "Low"

print("\nPrediction Result")
print("=================")
print(f"Readmission probability: {fresh_probability:.4f}")
print(f"Readmission probability: {fresh_probability * 100:.2f}%")
print(f"Decision threshold: {loaded_threshold:.2f}")
print(f"Predicted class: {fresh_prediction}")
print(f"Risk category: {risk_category}")

Fresh patient record created.
Input columns: 41
Processed feature shape: (1, 177)

Prediction Result
=================
Readmission probability: 0.3251
Readmission probability: 32.51%
Decision threshold: 0.30
Predicted class: 1
Risk category: Low

/tmp/ipykernel_2140/1012805127.py:35: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Caucasian' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fresh_patient.loc[0, column] = value
/tmp/ipykernel_2140/1012805127.py:35: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Female' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fresh_patient.loc[0, column] = value
/tmp/ipykernel_2140/1012805127.py:35: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[70-80)' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fresh_patient.loc[0, column] = value
/tmp/ipykernel_2140/1012805127.py:35: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Cardiology' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fresh_patient.loc[0, column] = value
/tmp/ipykernel_2140/1012805127.py:35: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '428' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fresh_patient.loc[0, column] = value
/tmp/ipykernel_2140/1012805127.py:35: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '250' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fresh_patient.loc[0, column] = value
/tmp/ipykernel_2140/1012805127.py:35: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '401' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fresh_patient.loc[0, column] = value
/tmp/ipykernel_2140/1012805127.py:35: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'None' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fresh_patient.loc[0, column] = value
/tmp/ipykernel_2140/1012805127.py:35: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'None' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fresh_patient.loc[0, column] = value
/tmp/ipykernel_2140/1012805127.py:35: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Steady' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fresh_patient.loc[0, column] = value
/tmp/ipykernel_2140/1012805127.py:35: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Yes' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fresh_patient.loc[0, column] = value
/tmp/ipykernel_2140/1012805127.py:35: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'No' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fresh_patient.loc[0, column] = value

In [107]:
# ============================================================
# STEP 6C — CLEAN DEPLOYMENT PREDICTION TEST
# ============================================================

# Create all expected columns as object dtype
fresh_patient = pd.DataFrame(
    [[np.nan] * len(expected_input_features)],
    columns=expected_input_features,
    dtype=object,
)

patient_values = {
    "race": "Caucasian",
    "gender": "Female",
    "age": "[70-80)",
    "admission_type_id": 1,
    "admission_source_id": 7,
    "medical_specialty": "Cardiology",
    "diag_1": "428",
    "diag_2": "250",
    "diag_3": "401",
    "max_glu_serum": "None",
    "A1Cresult": "None",
    "insulin": "Steady",
    "diabetesMed": "Yes",
    "change": "No",
    "number_inpatient": 3,
    "number_emergency": 2,
    "number_outpatient": 1,
    "number_diagnoses": 9,
}

for column, value in patient_values.items():
    if column in fresh_patient.columns:
        fresh_patient.loc[0, column] = value

# Transform using saved preprocessing
fresh_processed = loaded_pipeline.transform(
    fresh_patient
)

# Predict using saved model
fresh_probability = loaded_model.predict_proba(
    fresh_processed
)[0, 1]

fresh_prediction = int(
    fresh_probability >= loaded_threshold
)

# Risk category
if fresh_probability >= 0.70:
    risk_category = "High"
elif fresh_probability >= 0.40:
    risk_category = "Medium"
else:
    risk_category = "Low"

print("CLEAN DEPLOYMENT TEST")
print("=====================")
print("Input features:", fresh_patient.shape[1])
print("Processed features:", fresh_processed.shape[1])
print()
print(f"Readmission probability: {fresh_probability:.4f}")
print(f"Readmission probability: {fresh_probability * 100:.2f}%")
print(f"Decision threshold: {loaded_threshold:.2f}")
print(f"Predicted class: {fresh_prediction}")
print(f"Risk category: {risk_category}")

CLEAN DEPLOYMENT TEST
=====================
Input features: 41
Processed features: 177

Readmission probability: 0.3251
Readmission probability: 32.51%
Decision threshold: 0.30
Predicted class: 1
Risk category: Low

In [108]:
# ============================================================
# STEP 7 — GENERATE CLINICAL INSIGHTS
# ============================================================

clinical_insights = []

# Previous inpatient utilization
if patient_values.get("number_inpatient", 0) >= 2:
    clinical_insights.append(
        f"Patient has {patient_values['number_inpatient']} "
        "previous inpatient visits, indicating higher prior "
        "hospital utilization."
    )

# Emergency visits
if patient_values.get("number_emergency", 0) >= 1:
    clinical_insights.append(
        f"Patient has {patient_values['number_emergency']} "
        "previous emergency visit(s)."
    )

# Number of diagnoses
if patient_values.get("number_diagnoses", 0) >= 8:
    clinical_insights.append(
        f"Patient has {patient_values['number_diagnoses']} "
        "recorded diagnoses, suggesting greater clinical complexity."
    )

# Diabetes medication
if patient_values.get("diabetesMed") == "Yes":
    clinical_insights.append(
        "Patient is receiving diabetes medication."
    )

# Medication change
if patient_values.get("change") == "Yes":
    clinical_insights.append(
        "A medication change was recorded."
    )

# Age
if patient_values.get("age") in [
    "[70-80)",
    "[80-90)",
    "[90-100)",
]:
    clinical_insights.append(
        f"Patient belongs to the {patient_values['age']} age group."
    )

print("CLINICAL RISK INSIGHTS")
print("======================")

print(
    f"Readmission Probability: "
    f"{fresh_probability * 100:.2f}%"
)

print(f"Risk Category: {risk_category}")
print(
    f"Flagged for Readmission Risk: "
    f"{'Yes' if fresh_prediction == 1 else 'No'}"
)

print("\nSupporting Clinical Factors:")

if clinical_insights:
    for i, insight in enumerate(clinical_insights, 1):
        print(f"{i}. {insight}")
else:
    print("No significant supporting factors identified.")

CLINICAL RISK INSIGHTS
======================
Readmission Probability: 32.51%
Risk Category: Low
Flagged for Readmission Risk: Yes

Supporting Clinical Factors:
1. Patient has 3 previous inpatient visits, indicating higher prior hospital utilization.
2. Patient has 2 previous emergency visit(s).
3. Patient has 9 recorded diagnoses, suggesting greater clinical complexity.
4. Patient is receiving diabetes medication.
5. Patient belongs to the [70-80) age group.

In [109]:
# ============================================================
# STEP 8 — FINAL ARTIFACT VERIFICATION
# ============================================================

print("FINAL MODEL ARTIFACT VERIFICATION")
print("=" * 45)

print("Model name       :", loaded_artifact["model_name"])
print("Model version    :", loaded_artifact["model_version"])
print("Decision threshold:", loaded_artifact["decision_threshold"])
print("Input features   :", len(loaded_artifact["pipeline"].feature_names_in_))
print("Processed features:", loaded_artifact["n_features"])
print("Scale pos weight  :", loaded_artifact["scale_pos_weight"])

print("\nRemoved leakage-prone features:")
for feature in loaded_artifact["removed_features"]:
    print(" -", feature)

print("\nFinal test metrics:")
for metric, value in loaded_artifact["metrics"].items():
    print(f"{metric.upper():10}: {value:.4f}")

print("\nTop clinical drivers:")
for i, driver in enumerate(
    loaded_artifact["top_drivers"][:10],
    start=1
):
    print(
        f"{i:2}. "
        f"{driver['original_feature']}: "
        f"{driver['importance']:.4f}"
    )

# Final assertions
assert loaded_artifact["decision_threshold"] == 0.30
assert loaded_artifact["n_features"] == 177
assert len(loaded_artifact["pipeline"].feature_names_in_) == 41
assert len(loaded_artifact["removed_features"]) == 2
assert loaded_artifact["model_name"] == "xgboost_early_readmission"

print("\n" + "=" * 45)
print("FINAL ARTIFACT VERIFICATION PASSED")
print("=" * 45)

FINAL MODEL ARTIFACT VERIFICATION
=============================================
Model name       : xgboost_early_readmission
Model version    : v1
Decision threshold: 0.3
Input features   : 41
Processed features: 177
Scale pos weight  : 3.0

Removed leakage-prone features:
 - discharge_disposition_id
 - time_in_hospital

Final test metrics:
ACCURACY  : 0.7031
PRECISION : 0.1763
RECALL    : 0.4704
F1        : 0.2564
ROC_AUC   : 0.6517
PR_AUC    : 0.2017

Top clinical drivers:
 1. diag_1: 0.1507
 2. diag_2: 0.1367
 3. diag_3: 0.1176
 4. medical_specialty: 0.0672
 5. age: 0.0644
 6. number_inpatient: 0.0536
 7. admission_source_id: 0.0413
 8. admission_type_id: 0.0339
 9. race: 0.0318
10. max_glu_serum: 0.0228

=============================================
FINAL ARTIFACT VERIFICATION PASSED
=============================================

In [110]:
# ============================================================
# STEP 9 — CHECK FINAL TRAINING CONFIGURATION
# ============================================================

print("FINAL CONFIGURATION TO IMPLEMENT")
print("=" * 45)

print("Model name:", FINAL_MODEL_NAME)
print("Model version:", FINAL_MODEL_VERSION)
print("Threshold:", FINAL_THRESHOLD)
print("Scale pos weight:", FINAL_SCALE_POS_WEIGHT)

print("\nXGBoost parameters:")
print("n_estimators      :", 400)
print("max_depth         :", 5)
print("learning_rate     :", 0.03)
print("min_child_weight  :", 5)
print("subsample         :", 0.8)
print("colsample_bytree  :", 0.8)

print("\nLeakage-controlled features:")
print("- discharge_disposition_id → REMOVED")
print("- time_in_hospital         → REMOVED")

print("\nFinal test metrics:")
for metric, value in final_test_metrics.items():
    print(f"{metric.upper():10}: {value:.4f}")

FINAL CONFIGURATION TO IMPLEMENT
=============================================
Model name: xgboost_early_readmission
Model version: v1
Threshold: 0.3
Scale pos weight: 3.0

XGBoost parameters:
n_estimators      : 400
max_depth         : 5
learning_rate     : 0.03
min_child_weight  : 5
subsample         : 0.8
colsample_bytree  : 0.8

Leakage-controlled features:
- discharge_disposition_id → REMOVED
- time_in_hospital         → REMOVED

Final test metrics:
ACCURACY  : 0.7031
PRECISION : 0.1763
RECALL    : 0.4704
F1        : 0.2564
ROC_AUC   : 0.6517
PR_AUC    : 0.2017

In [111]:
print("NUMERICAL FEATURES:")
for i, feature in enumerate(no_leak_numeric_columns, start=1):
    print(f"{i:02d}. {feature}")

print("\nCATEGORICAL FEATURES:")
for i, feature in enumerate(no_leak_categorical_columns, start=1):
    print(f"{i:02d}. {feature}")

print("\nTOTAL:")
print("Numeric:", len(no_leak_numeric_columns))
print("Categorical:", len(no_leak_categorical_columns))
print("Total:", len(no_leak_numeric_columns) + len(no_leak_categorical_columns))

NUMERICAL FEATURES:
01. time_in_hospital
02. num_lab_procedures
03. num_procedures
04. num_medications
05. number_outpatient
06. number_emergency
07. number_inpatient
08. number_diagnoses

CATEGORICAL FEATURES:
01. race
02. gender
03. age
04. admission_type_id
05. admission_source_id
06. medical_specialty
07. diag_1
08. diag_2
09. diag_3
10. max_glu_serum
11. A1Cresult
12. metformin
13. repaglinide
14. nateglinide
15. chlorpropamide
16. glimepiride
17. acetohexamide
18. glipizide
19. glyburide
20. tolbutamide
21. pioglitazone
22. rosiglitazone
23. acarbose
24. miglitol
25. troglitazone
26. tolazamide
27. insulin
28. glyburide-metformin
29. glipizide-metformin
30. glimepiride-pioglitazone
31. metformin-rosiglitazone
32. metformin-pioglitazone
33. change
34. diabetesMed

TOTAL:
Numeric: 8
Categorical: 34
Total: 42

In [112]:
# ============================================================
# FINAL COLAB PROCESSED FEATURE CHECK
# ============================================================

fitted_feature_names = no_leak_preprocessor.get_feature_names_out()

print("Processed feature count:", len(fitted_feature_names))

print("\nFIRST 20 PROCESSED FEATURES:")
for i, feature in enumerate(fitted_feature_names[:20], start=1):
    print(f"{i:02d}. {feature}")

print("\nLAST 20 PROCESSED FEATURES:")
for i, feature in enumerate(
    fitted_feature_names[-20:],
    start=len(fitted_feature_names) - 19
):
    print(f"{i:03d}. {feature}")

Processed feature count: 178

FIRST 20 PROCESSED FEATURES:
01. numeric__time_in_hospital
02. numeric__num_lab_procedures
03. numeric__num_procedures
04. numeric__num_medications
05. numeric__number_outpatient
06. numeric__number_emergency
07. numeric__number_inpatient
08. numeric__number_diagnoses
09. categorical__race_AfricanAmerican
10. categorical__race_Caucasian
11. categorical__race_Hispanic
12. categorical__race_Missing
13. categorical__race_Other
14. categorical__race_infrequent_sklearn
15. categorical__gender_Female
16. categorical__gender_Male
17. categorical__gender_infrequent_sklearn
18. categorical__age_[20-30)
19. categorical__age_[30-40)
20. categorical__age_[40-50)

LAST 20 PROCESSED FEATURES:
159. categorical__troglitazone_infrequent_sklearn
160. categorical__tolazamide_No
161. categorical__tolazamide_infrequent_sklearn
162. categorical__insulin_Down
163. categorical__insulin_No
164. categorical__insulin_Steady
165. categorical__insulin_Up
166. categorical__glyburide-metformin_No
167. categorical__glyburide-metformin_infrequent_sklearn
168. categorical__glipizide-metformin_No
169. categorical__glipizide-metformin_infrequent_sklearn
170. categorical__glimepiride-pioglitazone_No
171. categorical__glimepiride-pioglitazone_infrequent_sklearn
172. categorical__metformin-rosiglitazone_No
173. categorical__metformin-rosiglitazone_infrequent_sklearn
174. categorical__metformin-pioglitazone_No
175. categorical__change_Ch
176. categorical__change_No
177. categorical__diabetesMed_No
178. categorical__diabetesMed_Yes

In [113]:
print("TRAINING DATA SHAPE USED BY COLAB PREPROCESSOR:")
print(X_train_no_leak.shape)

print("\nPATIENT COLUMN PRESENT:")
print("patient_nbr" in X_train_no_leak.columns)

print("\nPROCESSED FEATURE COUNT:")
print(len(fitted_feature_names))

print("\nFINAL COUNT AFTER REMOVING time_in_hospital:")
final_colab_features = [
    feature
    for feature in fitted_feature_names
    if feature != "numeric__time_in_hospital"
]

print(len(final_colab_features))

TRAINING DATA SHAPE USED BY COLAB PREPROCESSOR:
(79527, 42)

PATIENT COLUMN PRESENT:
False

PROCESSED FEATURE COUNT:
178

FINAL COUNT AFTER REMOVING time_in_hospital:
177

In [114]:
print("\nCOLAB TRAINING ROWS:")
print(len(X_train_no_leak))

print("\nCOLAB CATEGORICAL UNIQUE COUNTS:")
for column in no_leak_categorical_columns:
    print(
        f"{column:30s} "
        f"{X_train_no_leak[column].nunique(dropna=False)}"
    )

COLAB TRAINING ROWS:
79527

COLAB CATEGORICAL UNIQUE COUNTS:
race                           6
gender                         3
age                            10
admission_type_id              8
admission_source_id            17
medical_specialty              70
diag_1                         663
diag_2                         641
diag_3                         663
max_glu_serum                  4
A1Cresult                      4
metformin                      4
repaglinide                    4
nateglinide                    4
chlorpropamide                 3
glimepiride                    4
acetohexamide                  2
glipizide                      4
glyburide                      4
tolbutamide                    2
pioglitazone                   4
rosiglitazone                  4
acarbose                       4
miglitol                       4
troglitazone                   2
tolazamide                     3
insulin                        4
glyburide-metformin            4
glipizide-metformin            2
glimepiride-pioglitazone       2
metformin-rosiglitazone        2
metformin-pioglitazone         1
change                         2
diabetesMed                    2